import {buildPrismHome,summarizeProjects,buildHandoff,buildConferenceCall,resolveDispatchRoute,decisionLabel,buildActionIdentity,decideReplay} from './spectrum.mjs';
const state={snapshot:{works:[],live:false,monitorStatus:'UNKNOWN',monitor:{},capabilities:[]},capabilities:{COUNTER:false,DIRECT_API:false,DEVICE_BRIDGE:false}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const safe=(v,f='—')=>String(v??'').trim()||f;
const replayKey=id=>'prism:replay:'+id;
function readReplay(id){try{return JSON.parse(localStorage.getItem(replayKey(id))||'null');}catch{return null;}}
function writeReplay(id,value){try{localStorage.setItem(replayKey(id),JSON.stringify(value));}catch{}}

function humanStatus(v){const s=String(v||'').toUpperCase(),m={LIVE:'พร้อม',PASS:'ผ่าน',COMPLETE:'เสร็จแล้ว',MERGED:'รวมแล้ว','WAIT VERIFY':'รอตรวจ',WAIT:'กำลังรอ','ON PROCESS':'กำลังทำ',OPEN:'เปิดอยู่',UNKNOWN:'ยังไม่ทราบ',FAIL:'ไม่ผ่าน'};return m[s]||safe(v,'ยังไม่ทราบ');}
function statusClass(v){const s=String(v||'').toUpperCase();return ['LIVE','PASS','COMPLETE','MERGED'].includes(s)?'ok':s.includes('WAIT')||s==='UNKNOWN'?'wait':'info';}
function nav(page){$$('.page').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$$('.bottom-nav [data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===page));scrollTo({top:0,behavior:'instant'});}
function titleFor(w){return safe(w.title,'งานนี้');}
function workCard(w){const d=w.decision,l=d?decisionLabel(d.kind):humanStatus(w.status);return `<article class="work-card"><div class="work-top"><div><h3>${titleFor(w)}</h3><div class="subtle">${humanStatus(w.status)}${w.holder?' · อยู่กับ '+w.holder:''}</div></div><span class="status ${statusClass(d?.kind||w.status)}">${safe(l)}</span></div>${d?.summary?`<div class="decision-summary">${d.summary}</div>`:''}${d?.consequence?`<div class="impact">ถ้าดำเนินการ: ${d.consequence}</div>`:''}<div class="card-actions"><button data-detail="${w.workId}">ดูรายละเอียด</button><button class="primary-action" data-call-work="${w.workId}">ส่งต่อ</button></div></article>`;}
function addCopilot(text,who='app'){const t=$('#copilot-thread');const n=document.createElement('div');n.className='copilot-message '+who;n.textContent=text;t.append(n);t.scrollTop=t.scrollHeight;}
function fillWorks(works){const s=$('#handoff-work-select');s.innerHTML='<option value="">เลือกงาน</option>'+works.map((w,i)=>`<option value="${i}">${titleFor(w)}</option>`).join('');}
function prefill(w){if(!w)return;$('#handoff-work').value=safe(w.workId,'');$('#handoff-checkpoint').value=safe(w.checkpointId,'');const a=buildPrismHome(state.snapshot).active,i=a.findIndex(x=>x.workId===w.workId);if(i>=0)$('#handoff-work-select').value=String(i);}
function render(){
 const home=buildPrismHome(state.snapshot),sum=summarizeProjects(state.snapshot);
 $('#decision-count').textContent=home.decisions.length;
 for(const [id,items,empty] of [['decision-list',home.decisions,'ยังไม่มีเรื่องที่ต้องตัดสินใจ'],['work-list',home.active,'ยังไม่มีโปรเจกต์ที่กำลังทำ']]){const n=$('#'+id);n.className='stack'+(items.length?'':' empty-card');n.innerHTML=items.length?items.map(workCard).join(''):empty;}
 $('#project-active-count').textContent=sum.active;$('#project-wait-count').textContent=sum.waiting;$('#project-decision-count').textContent=sum.decision;fillWorks(home.active);
 const f=home.active[0];$('#m-live').textContent=home.live?'พร้อม':'ยังไม่ทราบ';$('#m-work').textContent=f?titleFor(f):'—';$('#m-route').textContent=f?.route?.length?f.route.join(' → '):'—';$('#m-ci').textContent=humanStatus(state.snapshot.monitor?.ci);$('#m-deploy').textContent=humanStatus(state.snapshot.monitor?.deploy);$('#m-provenance').textContent=humanStatus(state.snapshot.monitor?.provenance);$('#monitor-raw').textContent=JSON.stringify(state.snapshot,null,2);
 $$('[data-detail]').forEach(b=>b.onclick=()=>nav('MONITOR'));$$('[data-call-work]').forEach(b=>b.onclick=()=>{prefill(home.active.find(w=>w.workId===b.dataset.callWork));nav('HANDOFF');});
}
async function loadSnapshot(){const bridge=window.PRISM_BRIDGE;if(bridge?.getSnapshot){try{const x=await bridge.getSnapshot();if(x&&typeof x==='object')state.snapshot=x;if(bridge.getCapabilities)state.capabilities=await bridge.getCapabilities();}catch(e){state.snapshot={...state.snapshot,live:false,error:String(e?.message||e)};}}render();updateRoute();}
function updateRoute(){const r=resolveDispatchRoute(state.capabilities);$('#route-preview').textContent=r.route==='MANUAL'?'ยังไม่มีเส้นส่งสดที่พิสูจน์แล้ว — PRISM จะเตรียม handoff ให้':'พร้อมส่งและรอ readback จากปลายทาง';}
async function submitIntent(text){const bridge=window.PRISM_BRIDGE;addCopilot(text,'user');if(!bridge?.submitIntent){addCopilot('ตอนนี้ยังเชื่อม Copilot runtime จริงไม่ได้ แต่คำสั่งนี้จะไม่ถูกแกล้งว่าส่งสำเร็จ');return;}try{const r=await bridge.submitIntent(text);addCopilot(safe(r?.summary,'รับคำสั่งแล้ว'));await loadSnapshot();}catch(e){addCopilot('ยังทำให้ไม่ได้ตอนนี้: '+safe(e?.message,'ไม่ทราบสาเหตุ'));}}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
$$('[data-prompt]').forEach(b=>b.addEventListener('click',()=>submitIntent(b.dataset.prompt)));
$('#refresh').addEventListener('click',loadSnapshot);
$('#command-form').addEventListener('submit',e=>{e.preventDefault();const i=$('#command-input'),t=i.value.trim();if(!t)return;i.value='';submitIntent(t);});
$('#handoff-work-select').addEventListener('change',e=>prefill(buildPrismHome(state.snapshot).active[Number(e.target.value)]));
$('#handoff-form').addEventListener('input',updateRoute);
$('#handoff-form').addEventListener('submit',async e=>{e.preventDefault();const env=buildHandoff({workId:$('#handoff-work').value,checkpointId:$('#handoff-checkpoint').value,destination:$('#handoff-destination').value,requestedResult:$('#handoff-result').value,message:$('#handoff-message').value});const box=$('#handoff-readback');box.hidden=false;if(!env.ready){box.innerHTML='<strong>ยังส่งไม่ได้</strong><span>เลือกงานและผลที่ต้องการให้ครบก่อน</span>';return;}const route=resolveDispatchRoute(state.capabilities),bridge=window.PRISM_BRIDGE;if(route.route==='MANUAL'||!bridge?.dispatch){box.innerHTML='<strong>เตรียม Handoff แล้ว</strong><span>ยังไม่มีเส้นส่งสดที่พิสูจน์แล้ว จึงยังไม่ถือว่าส่งสำเร็จ</span>';return;}const actionIdentity=buildActionIdentity(env),prior=readReplay(actionIdentity),replay=decideReplay({actionIdentity,receipt:prior?.receipt,evidence:prior?.evidence});if(replay.decision==='RETURN_EXISTING'){box.innerHTML='<strong>งานนี้ส่งสำเร็จไปแล้ว</strong><span>'+safe(prior?.receipt?.summary,'ใช้ผลเดิมที่ยืนยันแล้ว — ไม่ส่งซ้ำ')+'</span>';return;}if(replay.decision==='WAIT_VERIFY'){box.innerHTML='<strong>รอตรวจผลเดิมก่อน</strong><span>มี receipt/evidence ของคำสั่งนี้ที่ยังยืนยันไม่ครบ จึงไม่ส่งซ้ำ</span>';return;}writeReplay(actionIdentity,{receipt:{actionIdentity,status:'UNKNOWN'},evidence:[]});try{const r=await bridge.dispatch({...env,route:route.route,actionIdentity});const evidence=Array.isArray(r?.evidence)?r.evidence.filter(Boolean):[];const status=String(r?.status||'UNKNOWN').toUpperCase();writeReplay(actionIdentity,{receipt:{actionIdentity,status,summary:safe(r?.summary,'')},evidence});const verified=decideReplay({actionIdentity,receipt:{actionIdentity,status},evidence});box.innerHTML=verified.decision==='RETURN_EXISTING'?'<strong>ส่งแล้ว</strong><span>'+safe(r?.summary,'ปลายทางรับ Work แล้ว')+'</span>':'<strong>ส่งแล้ว รอตรวจ</strong><span>ได้รับผลจากปลายทาง แต่ evidence/readback ยังไม่ครบ จึงล็อกการส่งซ้ำไว้ก่อน</span>';await loadSnapshot();}catch(err){writeReplay(actionIdentity,{receipt:{actionIdentity,status:'UNKNOWN',summary:safe(err?.message,'')},evidence:[]});box.innerHTML='<strong>ส่งไม่สำเร็จ</strong><span>'+safe(err?.message,'ไม่ทราบสาเหตุ')+' — ล็อก retry ไว้จนกว่าจะตรวจผลเดิม</span>';}});
$('#conference-go-light').addEventListener('click',async()=>{const call=buildConferenceCall({workId:$('#handoff-work').value,checkpointId:$('#handoff-checkpoint').value,participants:['GO','LIGHT']});const box=$('#handoff-readback');box.hidden=false;if(!call.ready){box.innerHTML='<strong>ยังเรียกไม่ได้</strong><span>เลือก Work ก่อน</span>';return;}const bridge=window.PRISM_BRIDGE;if(!bridge?.conference){box.innerHTML='<strong>เตรียมห้องคุยแล้ว</strong><span>GO + LIGHT จะใช้ Work เดียวกัน แต่ live conference bridge ยังไม่ถูกพิสูจน์ จึงยังไม่ถือว่าเรียกสำเร็จ</span>';return;}try{const r=await bridge.conference(call);box.innerHTML='<strong>เรียกแล้ว</strong><span>'+safe(r?.summary,'GO และ LIGHT เข้ารอบ Work นี้แล้ว')+'</span>';}catch(e){box.innerHTML='<strong>เรียกไม่สำเร็จ</strong><span>'+safe(e?.message,'ไม่ทราบสาเหตุ')+'</span>';}});
$('#open-ride-mode').addEventListener('click',()=>{$('#ride-mode').hidden=false;});
$('[data-finance-prompt]').addEventListener('click',()=>{nav('COPILOT');$('#command-input').value='สรุปการเงินจาก Ledger ให้ผม';$('#command-input').focus();});
$$('[data-capability]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.capability==='PROJECTS')nav('PROJECTS');if(b.dataset.capability==='HANDOFF')nav('HANDOFF');}));
loadSnapshot();