"use strict";
const RELEASE='5.2.6';
const ASSET_REVISION='sha256-014be90145c94c06';
const CACHE=`ygph-metropolis-${RELEASE}-${ASSET_REVISION}`;
const SHELL=['./index.html','./app.mjs','./styles.css','./theme.css','./compact-ui.css','./manifest.webmanifest','./icon-192.png','./icon-512.png','./ui/app.mjs','./ui/release-status.mjs','./ui/reset-all-ui.mjs','./ui/theme-shell.mjs','./ui/home-ui.mjs','./ui/store-ui.mjs','./ui/finance-ui.mjs','./ui/ride-ui.mjs','./ui/action-popups.mjs','./ui/obligation-import-ui.mjs','./ui/ui-model.mjs','./ui/product-model.mjs','./ui/icons.mjs','./ui/master-input.mjs','./ui/master-input.css','./greenfield/action-contract.mjs','./greenfield/calculation-authority.mjs','./greenfield/daily-lifecycle.mjs','./greenfield/runtime.mjs','./greenfield/device-unlock.mjs','./greenfield/first-run.mjs','./greenfield/core.mjs','./greenfield/persistence.mjs','./greenfield/browser-store.mjs','./greenfield/cutover.mjs','./greenfield/evidence-integrity.mjs','./greenfield/finance-seed-import.mjs','./greenfield/import-evidence.mjs','./greenfield/import-router.mjs','./greenfield/projections.mjs','./greenfield/restore-compat.mjs','./greenfield/obligation-import.mjs','./greenfield/command-runtime.mjs','./greenfield/domain-operations.mjs','./greenfield/ride-domain.mjs','./greenfield/ride-workflows.mjs','./greenfield/master-input-router.mjs','./greenfield/workflow-runtime.mjs','./greenfield/workflow-invariants.mjs','./greenfield/mutation-coordinator.mjs','./greenfield/business-workflows.mjs','./greenfield/backup.mjs'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('ygph-metropolis-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
async function navigationNetworkFirst(request){try{const response=await fetch(request,{cache:'no-store'});if(response&&response.status===200&&response.type!=='opaque'){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put('./index.html',copy));}return response;}catch(error){const cached=await caches.match('./index.html');if(cached)return cached;throw error;}}
async function assetCacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response&&response.status===200&&response.type!=='opaque'){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy));}return response;}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;if(event.request.mode==='navigate'){event.respondWith(navigationNetworkFirst(event.request));return;}event.respondWith(assetCacheFirst(event.request));});