const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const entry=fs.readFileSync(path.join(root,'app.mjs'),'utf8');
function between(source,startMarker,endMarker){const start=source.indexOf(startMarker);assert.notEqual(start,-1,`missing start marker: ${startMarker}`);const end=source.indexOf(endMarker,start+startMarker.length);assert.notEqual(end,-1,`missing end marker: ${endMarker}`);return source.slice(start,end);}
test('locked login surface exposes only password, sign in, and forgot password actions',()=>{const header=between(html,'<header class="appbar">','</header>');const loginSurface=between(html,'<section id="gate"','<section id="recoveryPanel"');assert.match(header,/YGPH METROPOLIS/);assert.doesNotMatch(header,/Functional Shell|LOCKED|Vault|Recovery|crypto/);assert.match(loginSurface,/<label>รหัสผ่าน\s*<input id="devicePin"[^>]*autocomplete="current-password"/);assert.match(loginSurface,/<button id="unlockBtn"[^>]*>เข้าสู่ระบบ<\/button>/);assert.match(loginSurface,/<button id="forgotPasswordBtn"[^>]*>ลืมรหัสผ่าน\?<\/button>/);for(const forbidden of ['Vault','Device PIN','Evidence','Backup','Recovery','crypto'])assert.equal(loginSurface.includes(forbidden),false);assert.equal((loginSurface.match(/<input\b/g)||[]).length,1);assert.equal((loginSurface.match(/<button\b/g)||[]).length,2);assert.equal(loginSurface.includes('<details'),false);});
test('forgot password is staged as Recovery Code then new password while data recovery stays advanced',()=>{const recoverySurface=between(html,'<section id="recoveryPanel"','<div id="workspace"');for(const pattern of [/id="recoveryPanel"[^>]*class="[^"]*hidden/,/<h1>กู้คืนการเข้าถึง<\/h1>/,/id="recoveryVerifyStep"/,/<label>รหัสกู้คืน\s*<input id="recoveryPassphrase"/,/id="verifyRecoveryBtn"[^>]*>ตรวจสอบรหัสกู้คืน<\/button>/,/id="recoveryResetStep"[^>]*class="[^"]*hidden/,/<label>รหัสผ่านใหม่\s*<input id="recoveryNewPassword"/,/<label>ยืนยันรหัสผ่าน\s*<input id="recoveryConfirmPassword"/,/id="resetPasswordBtn"[^>]*>ตั้งรหัสผ่านใหม่<\/button>/,/id="lockedAdvancedRecovery"/,/id="evidenceFile"/,/id="restoreFile"/])assert.match(recoverySurface,pattern);assert.match(entry,/verifyGreenfieldRecoveryCode/);assert.match(entry,/resetGreenfieldDevicePassword/);assert.match(entry,/\$\('verifyRecoveryBtn'\)\.addEventListener\('click'/);assert.match(entry,/\$\('resetPasswordBtn'\)\.addEventListener\('click'/);assert.doesNotMatch(entry,/\$\('enrollDeviceBtn'\)\.click\(\)|\$\('importEvidenceBtn'\)\.click\(\)|\$\('restoreBtn'\)\.click\(\)/);});
test('Settings utility exposes flat security backup and system sections',()=>{const settings=between(html,'<dialog id=\"settingsDialog\"','</dialog>');assert.match(html,/id=\"settingsBtn\"[^>]*aria-label=\"ตั้งค่า\"/);const primaryNav=between(html,'<nav id=\"bottomNav\"','</nav>');assert.doesNotMatch(primaryNav,/data-destination=\"system\"|aria-label=\"ตั้งค่า\"/);for(const label of ['ความปลอดภัย','สำรองและกู้คืน','ระบบ'])assert.match(settings,new RegExp(label));assert.doesNotMatch(settings,/<details\b/);for(const id of ['changePasswordBtn','backupBtn','openRestoreRouteBtn','runtimeBadge','diagnostics'])assert.match(settings,new RegExp(`id=\"${id}\"`));});
test('authenticated password change stays inside settings and never asks for Recovery Code',()=>{const settings=between(html,'<dialog id=\"settingsDialog\"','</dialog>');const changePanel=between(settings,'<div id=\"changePasswordPanel\"','</section>');for(const pattern of [/class=\"[^\"]*hidden/,/<label>รหัสผ่านปัจจุบัน\s*<input id=\"changeCurrentPassword\"/,/<label>รหัสผ่านใหม่\s*<input id=\"changeNewPassword\"/,/<label>ยืนยันรหัสผ่าน\s*<input id=\"changeConfirmPassword\"/,/id=\"submitChangePasswordBtn\"/,/id=\"cancelChangePasswordBtn\"/])assert.match(changePanel,pattern);assert.doesNotMatch(changePanel,/รหัสกู้คืน|recoveryPassphrase|Evidence|Backup/);assert.match(entry,/openGreenfieldRuntimeWithDevicePin/);assert.match(entry,/changeDevicePassword/);assert.match(entry,/\$\('changePasswordBtn'\)\.addEventListener\('click'/);assert.match(entry,/\$\('submitChangePasswordBtn'\)\.addEventListener\('click'/);});
test('authentication and recovery errors stay user-facing',()=>{for(const pattern of [/DEVICE_PIN_INVALID[\s\S]*รหัสผ่านไม่ถูกต้อง/,/DEVICE_PIN_TOO_SHORT[\s\S]*รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร/,/เครื่องนี้ยังไม่ได้ตั้งรหัสเข้าแอป[\s\S]*ลืมรหัสผ่าน\?/,/DEVICE_UNLOCK_INCOMPLETE[\s\S]*ลืมรหัสผ่าน\?/,/GREENFIELD_VAULT_DECRYPT_FAILED[\s\S]*รหัสกู้คืนไม่ถูกต้อง/,/PASSPHRASE_TOO_SHORT[\s\S]*รหัสกู้คืนไม่ถูกต้อง/,/GREENFIELD_NOT_INITIALIZED[\s\S]*ไม่พบข้อมูลเดิมในเครื่องนี้/,/INVALID_GREENFIELD_[\s\S]*ไม่สามารถกู้คืนการเข้าถึงได้/])assert.match(entry,pattern);});
test('recovery secrets are cleared when leaving recovery or opening workspace',()=>{for(const pattern of [/verifiedRecoveryCode\s*=\s*''/,/\$\('recoveryPassphrase'\)\.value\s*=\s*''/,/\$\('recoveryNewPassword'\)\.value\s*=\s*''/,/\$\('recoveryConfirmPassword'\)\.value\s*=\s*''/])assert.match(entry,pattern);});
