const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const entry=fs.readFileSync(path.join(root,'app.mjs'),'utf8');
function between(source,startMarker,endMarker){const start=source.indexOf(startMarker);assert.notEqual(start,-1,`missing start marker: ${startMarker}`);const end=source.indexOf(endMarker,start+startMarker.length);assert.notEqual(end,-1,`missing end marker: ${endMarker}`);return source.slice(start,end);}
test('locked login surface exposes only password, sign in, and recovery entry actions',()=>{const header=between(html,'<header class="appbar">','</header>');const loginSurface=between(html,'<section id="gate"','<section id="recoveryPanel"');assert.match(header,/YGPH METROPOLIS/);assert.doesNotMatch(header,/Functional Shell|LOCKED|Vault|Recovery|crypto/);assert.match(loginSurface,/<label>รหัสผ่าน\s*<input id="devicePin"[^>]*autocomplete="current-password"/);assert.match(loginSurface,/<button id="unlockBtn"[^>]*>เข้าสู่ระบบ<\/button>/);assert.match(loginSurface,/id="forgotPasswordBtn"/);for(const forbidden of ['Vault','Device PIN','Evidence','Backup','Recovery','crypto'])assert.equal(loginSurface.includes(forbidden),false);assert.equal((loginSurface.match(/<input\b/g)||[]).length,1);assert.equal((loginSurface.match(/<button\b/g)||[]).length,2);assert.equal(loginSurface.includes('<details'),false);});
test('first run is a two-field setup: password and recovery code only',()=>{assert.match(entry,/inspectGreenfieldDeviceUnlock/);assert.match(entry,/function showFirstSetup\(\)/);assert.match(entry,/id="firstPassword"/);assert.match(entry,/id="firstRecoveryCode"/);assert.match(entry,/id="createFirstSetupBtn"/);assert.match(entry,/initializeFirstRun/);const setup=/function showFirstSetup\(\)[\s\S]*?function showRecovery/.exec(entry)?.[0]||'';assert.doesNotMatch(setup,/type="file"|restoreFile|Evidence|Backup|อัปโหลด|ไฟล์สำรอง/);});
test('recovery entry remains one direct file action and does not leak into first-run setup',()=>{assert.match(entry,/function showRecovery\(\)/);assert.match(entry,/เลือกไฟล์สำรอง ระบบจะตรวจสอบไฟล์ให้เองก่อนกู้คืน/);assert.match(entry,/id="restoreFile"/);assert.match(entry,/id="directRestoreBtn"/);assert.match(entry,/openGreenfieldRuntimeFromBackup/);assert.doesNotMatch(entry,/verifyGreenfieldRecoveryCode|resetGreenfieldDevicePassword|importEvidenceBtn|evidenceFile/);});
test('Settings utility exposes flat security backup and system sections',()=>{const settings=between(html,'<dialog id=\"settingsDialog\"','</dialog>');assert.match(html,/id=\"settingsBtn\"[^>]*aria-label=\"ตั้งค่า\"/);const primaryNav=between(html,'<nav id=\"bottomNav\"','</nav>');assert.doesNotMatch(primaryNav,/data-destination=\"system\"|aria-label=\"ตั้งค่า\"/);for(const label of ['ความปลอดภัย','สำรองและกู้คืน','ระบบ'])assert.match(settings,new RegExp(label));assert.doesNotMatch(settings,/<details\b/);for(const id of ['changePasswordBtn','backupBtn','openRestoreRouteBtn','runtimeBadge','diagnostics'])assert.match(settings,new RegExp(`id=\"${id}\"`));});
test('authenticated password change stays inside settings and never asks for Recovery Code',()=>{const settings=between(html,'<dialog id=\"settingsDialog\"','</dialog>');const changePanel=between(settings,'<div id=\"changePasswordPanel\"','</section>');for(const pattern of [/class=\"[^\"]*hidden/,/<label>รหัสผ่านปัจจุบัน\s*<input id=\"changeCurrentPassword\"/,/<label>รหัสผ่านใหม่\s*<input id=\"changeNewPassword\"/,/<label>ยืนยันรหัสผ่าน\s*<input id=\"changeConfirmPassword\"/,/id=\"submitChangePasswordBtn\"/,/id=\"cancelChangePasswordBtn\"/])assert.match(changePanel,pattern);assert.doesNotMatch(changePanel,/รหัสกู้คืน|recoveryPassphrase|Evidence|Backup/);assert.match(entry,/openGreenfieldRuntimeWithDevicePin/);assert.match(entry,/changeDevicePassword/);});
test('authentication and recovery errors stay user-facing',()=>{for(const pattern of [/DEVICE_PIN_INVALID[\s\S]*รหัสผ่านไม่ถูกต้อง/,/DEVICE_PIN_TOO_SHORT[\s\S]*รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร/,/DEVICE_UNLOCK_INCOMPLETE[\s\S]*กู้คืนจากไฟล์สำรอง/,/GREENFIELD_VAULT_DECRYPT_FAILED[\s\S]*ไฟล์สำรองเปิดไม่ได้หรือข้อมูลไม่สมบูรณ์/,/INVALID_GREENFIELD_[\s\S]*ไฟล์นี้ไม่ใช่ไฟล์สำรองที่ METRO ใช้ได้/])assert.match(entry,pattern);assert.match(entry,/restoreErrorText/);});
test('existing data is never silently overwritten',()=>{assert.match(entry,/GREENFIELD_RESTORE_CONFIRM_REQUIRED/);assert.match(entry,/กู้คืนไฟล์นี้แทนที่ข้อมูลปัจจุบันหรือไม่/);assert.match(entry,/performRestore\(backup, false\)/);assert.match(entry,/performRestore\(backup, true\)/);});
