package com.big.gobrowser.outsideview

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.nio.file.Files
import java.nio.file.StandardCopyOption

class MapStateStore(private val root: File) {
    constructor(context: Context):this(File(context.filesDir,"outside-view"))
    private val file get()=File(root,"journal.json")
    fun load():MapJournal { if(!file.exists())return MapJournal(MapState()); return runCatching{decode(JSONObject(file.readText()))}.getOrElse{MapJournal(MapState())} }
    @Synchronized fun commit(journal:MapJournal){require(journal.version==1);root.mkdirs();val tmp=File(root,"journal.json.tmp");java.io.FileOutputStream(tmp).use{it.write(encode(journal).toString().toByteArray());it.fd.sync()};try{Files.move(tmp.toPath(),file.toPath(),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING)}catch(e:Exception){tmp.delete();throw IllegalStateException("atomic journal replacement unavailable",e)}}
    private fun nullable(v:String?):Any=v?:JSONObject.NULL
    private fun nullable(v:Long?):Any=v?:JSONObject.NULL
    private fun b(v:Bounds)=JSONObject().put("west",v.west).put("south",v.south).put("east",v.east).put("north",v.north)
    private fun encode(j:MapJournal):JSONObject { val s=JSONObject().put("revision",j.state.revision); val z=JSONArray();j.state.zones.values.forEach{z.put(MapCommandCodec.encode(MapCommand("_",MapAction.UPSERT_ZONE,zone=it)).getJSONObject("zone"))};val g=JSONArray();j.state.grids.values.forEach{g.put(MapCommandCodec.encode(MapCommand("_",MapAction.UPSERT_GRID,grid=it)).getJSONObject("grid"))};val p=JSONArray();j.state.pins.values.forEach{p.put(MapCommandCodec.encode(MapCommand("_",MapAction.UPSERT_PIN,pin=it)).getJSONObject("pin"))};val notes=JSONObject();j.state.notes.forEach{(k,v)->notes.put(k,v)};val rec=JSONArray();j.state.recommendations.forEach{rec.put(it)};val hi=JSONArray();j.state.highlights.forEach{hi.put(it)};s.put("zones",z).put("grids",g).put("pins",p).put("notes",notes).put("recommendations",rec).put("highlights",hi).put("focused",nullable(j.state.focused));val hashes=JSONObject();j.hashes.forEach{(k,v)->hashes.put(k,v)};val receipts=JSONObject();j.receipts.forEach{(k,v)->receipts.put(k,JSONObject().put("commandId",v.commandId).put("status",v.status.name).put("reason",nullable(v.reason)).put("revision",v.revision).put("rendererToken",nullable(v.rendererToken)).put("confirmedFeatureIds",JSONArray(v.confirmedFeatureIds.toList())))};val pending=j.pending?.let{JSONObject().put("command",MapCommandCodec.encode(it.command)).put("revision",it.revision).put("token",it.token)}?:JSONObject.NULL;return JSONObject().put("version",j.version).put("state",s).put("hashes",hashes).put("receipts",receipts).put("pending",pending)}
    private fun text(o:JSONObject,k:String)=if(o.isNull(k))null else o.optString(k,"")
    private fun decode(o:JSONObject):MapJournal{require(o.optInt("version",1)==1);val s=o.getJSONObject("state");val zones=linkedMapOf<String,Zone>();val grids=linkedMapOf<String,Grid>();val pins=linkedMapOf<String,Pin>();val za=s.optJSONArray("zones")?:JSONArray();for(i in 0 until za.length()){val z=MapCommandCodec.decode(JSONObject().put("commandId","_").put("action","UPSERT_ZONE").put("zone",za.getJSONObject(i)));zones[z.zone!!.id]=z.zone};val ga=s.optJSONArray("grids")?:JSONArray();for(i in 0 until ga.length()){val g=MapCommandCodec.decode(JSONObject().put("commandId","_").put("action","UPSERT_GRID").put("grid",ga.getJSONObject(i)));grids[g.grid!!.id]=g.grid};val pa=s.optJSONArray("pins")?:JSONArray();for(i in 0 until pa.length()){val p=MapCommandCodec.decode(JSONObject().put("commandId","_").put("action","UPSERT_PIN").put("pin",pa.getJSONObject(i)));pins[p.pin!!.id]=p.pin};val notes=mutableMapOf<String,String>();s.optJSONObject("notes")?.keys()?.forEach{notes[it]=s.getJSONObject("notes").getString(it)};fun set(k:String)=buildSet{val a=s.optJSONArray(k)?:JSONArray();for(i in 0 until a.length())add(a.getString(i))};val state=MapState(zones,grids,pins,notes,set("recommendations"),set("highlights"),text(s,"focused"),s.optLong("revision"));val hashes=mutableMapOf<String,String>();o.optJSONObject("hashes")?.keys()?.forEach{hashes[it]=o.getJSONObject("hashes").getString(it)};val receipts=mutableMapOf<String,MapReceipt>();o.optJSONObject("receipts")?.keys()?.forEach{val r=o.getJSONObject("receipts").getJSONObject(it);val ids=buildSet{val a=r.optJSONArray("confirmedFeatureIds")?:JSONArray();for(i in 0 until a.length())add(a.getString(i))};receipts[it]=MapReceipt(r.getString("commandId"),MapReceiptStatus.valueOf(r.getString("status")),text(r,"reason"),r.optLong("revision"),text(r,"rendererToken"),ids)};val po=o.optJSONObject("pending");val pending=po?.let{val c=MapCommandCodec.decode(it.getJSONObject("command"));PendingRender(c,it.getLong("revision"),it.getString("token"))};return MapJournal(state,pending,hashes,receipts)}
}
