import { parseGeneralIncome } from './general-income.mjs';
import { parseStoreSale } from './store-sale.mjs';
import { formatThaiBangkokDate } from './bangkok-date.mjs';
import { createLighthouseRuntimeGate, authMessage } from './runtime-gate.mjs';
import { createLighthouseLedgerBridge } from './runtime-ledger.mjs';

const STORAGE_KEY = 'lighthouse-next-demo-v1';
const AMBIGUITY_LOCK = 'BABA';
const DEFAULT_PRODUCTS = Object.freeze([
  { id: 'phone', name: 'มือถือ', aliases: ['โทรศัพท์', 'โทสับ'], stock: 5 },
  { id: 'case', name: 'เคสมือถือ', aliases: ['เคส'], stock: 8 },
  { id: 'film', name: 'ฟิล์ม', aliases: ['ฟิล์มกันรอย'], stock: 12 },
]);
const DEFAULT_OBLIGATIONS = Object.freeze([{ id: 'next-expense', title: 'ค่าใช้จ่ายก้อนถัดไป', amount: 3200, dueLabel: 'อีก 3 วัน', dailyTarget: 1100, status: 'OPEN' }]);
const DEFAULT_STATE = Object.freeze({ activeRoot: 'home', chatHistory: [], pendingFlow: null, manualView: null, products: DEFAULT_PRODUCTS, obligations: DEFAULT_OBLIGATIONS, transactions: [], cash: 2450, expectedIncome: 700, todayIncome: 1250, todayExpense: 380 });

const root = document.querySelector('#demo-root');
const authScreen = root.querySelector('#auth-screen');
const appShell = root.querySelector('#app-shell');
const loginForm = root.querySelector('#login-form');
const devicePassword = root.querySelector('#device-password');
const loginSubmit = root.querySelector('#login-submit');
const showRecoveryButton = root.querySelector('#show-recovery');
const recoveryForm = root.querySelector('#recovery-form');
const recoveryCodeInput = root.querySelector('#recovery-code');
const newPasswordInput = root.querySelector('#new-password');
const confirmPasswordInput = root.querySelector('#confirm-password');
const cancelRecoveryButton = root.querySelector('#cancel-recovery');
const authStatus = root.querySelector('#auth-status');
const setupRequired = root.querySelector('#setup-required');
const lockAppButton = root.querySelector('#lock-app');
const homeDate = root.querySelector('#home-date');
const homeCashValue = root.querySelector('#home-cash-value');
const homeExpectedValue = root.querySelector('#home-expected-value');
const homeIncomeValue = root.querySelector('#home-income-value');
const homeExpenseValue = root.querySelector('#home-expense-value');
const homeNetValue = root.querySelector('#home-net-value');
const homeObligationTitle = root.querySelector('#home-obligation-title');
const homeObligationDue = root.querySelector('#home-obligation-due');
const homeObligationValue = root.querySelector('#home-obligation-value');
const homeGapValue = root.querySelector('#home-gap-value');
const homeTargetValue = root.querySelector('#home-target-value');
const pageKicker = root.querySelector('#page-kicker');
const chatThread = root.querySelector('#chat-thread');
const chatActions = root.querySelector('#chat-actions');
const chatForm = root.querySelector('#chat-form');
const chatInput = root.querySelector('#chat-input');
const chatSend = root.querySelector('#chat-send');
const manualHub = root.querySelector('#manual-hub');
const manualDetail = root.querySelector('#manual-detail');
const manualDetailContent = root.querySelector('#manual-detail-content');
const resetDialog = root.querySelector('#reset-dialog');
const runtimeGate = createLighthouseRuntimeGate();
const ledgerBridge = createLighthouseLedgerBridge();

let pendingReversalSaleId = null;
let state = loadState();
let ledgerTruth = null;
let realIncomeCommitBusy = false;

function newOperationId(prefix) { const suffix = globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`; return `${prefix}-${suffix}`; }
function ensureGeneralIncomeIdentity(pending) { if (!pending.workflowId) pending.workflowId = newOperationId('WF-LH-INCOME'); if (!pending.ledgerTransactionId) pending.ledgerTransactionId = newOperationId('TX-LH-INCOME'); saveState(); return pending; }
function freshProducts() { return DEFAULT_PRODUCTS.map((product) => ({ ...product, aliases: [...product.aliases] })); }
function freshObligations() { return DEFAULT_OBLIGATIONS.map((obligation) => ({ ...obligation })); }
function cloneDefaults() { return { activeRoot: DEFAULT_STATE.activeRoot, chatHistory: [], pendingFlow: null, manualView: null, products: freshProducts(), obligations: freshObligations(), transactions: [], cash: DEFAULT_STATE.cash, expectedIncome: DEFAULT_STATE.expectedIncome, todayIncome: DEFAULT_STATE.todayIncome, todayExpense: DEFAULT_STATE.todayExpense }; }
function numberOr(value, fallback) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function normalizeStoredProducts(products) { if (!Array.isArray(products)) return freshProducts(); return freshProducts().map((baseline) => { const stored = products.find((product) => product?.id === baseline.id); const stock = Number(stored?.stock); return { ...baseline, stock: Number.isInteger(stock) && stock >= 0 ? stock : baseline.stock }; }); }
function normalizeStoredObligations(obligations) { if (!Array.isArray(obligations)) return freshObligations(); return freshObligations().map((baseline) => { const stored = obligations.find((obligation) => obligation?.id === baseline.id); if (!stored) return baseline; const amount = numberOr(stored.amount, baseline.amount); const dailyTarget = numberOr(stored.dailyTarget, baseline.dailyTarget); return { ...baseline, title: typeof stored.title === 'string' && stored.title.trim() ? stored.title.trim() : baseline.title, amount: amount >= 0 ? amount : baseline.amount, dueLabel: typeof stored.dueLabel === 'string' && stored.dueLabel.trim() ? stored.dueLabel.trim() : baseline.dueLabel, dailyTarget: dailyTarget >= 0 ? dailyTarget : baseline.dailyTarget, status: stored.status === 'CLOSED' ? 'CLOSED' : 'OPEN' }; }); }
function normalizeStoredTransactions(transactions) { if (!Array.isArray(transactions)) return []; return transactions.filter((transaction) => transaction && transaction.id && transaction.type).slice(-100).map((transaction) => ({ ...transaction })); }
function storeSaleStage(pending) { if (!Number.isFinite(Number(pending.value)) || Number(pending.value) <= 0) return 'STORE_SALE_VALUE'; if (!Number.isInteger(Number(pending.quantity)) || Number(pending.quantity) <= 0) return 'STORE_SALE_QUANTITY'; return 'CONFIRM_STORE_SALE'; }
function normalizeStoredPending(pending) { if (!pending || typeof pending !== 'object') return null; if (pending.kind === 'GENERAL_INCOME') { if (!Number.isFinite(Number(pending.amount)) || Number(pending.amount) <= 0) return null; const source = typeof pending.source === 'string' && pending.source.trim() ? pending.source.trim() : null; const workflowId = typeof pending.workflowId === 'string' && pending.workflowId.trim() ? pending.workflowId.trim() : null; const ledgerTransactionId = typeof pending.ledgerTransactionId === 'string' && pending.ledgerTransactionId.trim() ? pending.ledgerTransactionId.trim() : null; return { kind:'GENERAL_INCOME', stage:source ? 'CONFIRM_GENERAL_INCOME' : 'GENERAL_INCOME_SOURCE', amount:Number(pending.amount), source, workflowId, ledgerTransactionId }; } if (pending.kind === 'STORE_SALE' && pending.productId && pending.productName) { const normalized = { kind: 'STORE_SALE', stage: pending.stage, productId: String(pending.productId), productName: String(pending.productName), value: Number.isFinite(Number(pending.value)) && Number(pending.value) > 0 ? Number(pending.value) : null, quantity: Number.isInteger(Number(pending.quantity)) && Number(pending.quantity) > 0 ? Number(pending.quantity) : null }; normalized.stage = storeSaleStage(normalized); return normalized; } return null; }
function loadState() { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return cloneDefaults(); const parsed = JSON.parse(raw); return { ...cloneDefaults(), ...parsed, chatHistory: Array.isArray(parsed.chatHistory) ? parsed.chatHistory.slice(-80) : [], pendingFlow: normalizeStoredPending(parsed.pendingFlow), products: normalizeStoredProducts(parsed.products), obligations: normalizeStoredObligations(parsed.obligations), transactions: normalizeStoredTransactions(parsed.transactions), cash: numberOr(parsed.cash, DEFAULT_STATE.cash), expectedIncome: numberOr(parsed.expectedIncome, DEFAULT_STATE.expectedIncome), todayIncome: numberOr(parsed.todayIncome, DEFAULT_STATE.todayIncome), todayExpense: numberOr(parsed.todayExpense, DEFAULT_STATE.todayExpense) }; } catch { return cloneDefaults(); } }
function saveState() { const snapshot = { activeRoot: ['home','chat','manual','settings'].includes(state.activeRoot) ? state.activeRoot : 'home', chatHistory: state.chatHistory.slice(-80), pendingFlow: state.pendingFlow, manualView: state.manualView, products: state.products, obligations: state.obligations, transactions: state.transactions.slice(-100), cash: state.cash, expectedIncome: state.expectedIncome, todayIncome: state.todayIncome, todayExpense: state.todayExpense }; try { localStorage.setItem(STORAGE_KEY, JSON.stringify(snapshot)); } catch {} }
function formatBaht(value) { return `฿${Number(value || 0).toLocaleString('en-US', { maximumFractionDigits: 2 })}`; }
function formatSatang(value) { return formatBaht(Number(value || 0) / 100); }
function financeSnapshot() { if (!ledgerTruth) return null; return { cashSatang:ledgerTruth.balanceSatang, todayIncomeSatang:ledgerTruth.todayInSatang, todayExpenseSatang:ledgerTruth.todayOutSatang, netSatang:ledgerTruth.netSatang }; }
function renderHomeTruth() { const snapshot = financeSnapshot(); homeCashValue.textContent = snapshot ? formatSatang(snapshot.cashSatang) : '—'; homeIncomeValue.textContent = snapshot ? formatSatang(snapshot.todayIncomeSatang) : '—'; homeExpenseValue.textContent = snapshot ? formatSatang(snapshot.todayExpenseSatang) : '—'; homeNetValue.textContent = snapshot ? `${snapshot.netSatang >= 0 ? '+' : '-'}${formatSatang(Math.abs(snapshot.netSatang))}` : '—'; homeExpectedValue.textContent = '—'; homeObligationTitle.textContent = 'ยังไม่เชื่อมข้อมูลจริง'; homeObligationDue.textContent = '—'; homeObligationValue.textContent = '—'; homeGapValue.textContent = '—'; homeTargetValue.textContent = '—'; }
function resetDemoState() { state = cloneDefaults(); pendingReversalSaleId = null; try { localStorage.removeItem(STORAGE_KEY); } catch {} renderHomeTruth(); manualDetail.hidden = true; manualHub.hidden = false; selectRoot('home'); }

function setAuthBusy(busy) { loginSubmit.disabled = busy; devicePassword.disabled = busy; showRecoveryButton.disabled = busy; }
function showLoginGate(message = 'พร้อมเข้าสู่ LIGHTHOUSE') { authScreen.hidden = false; appShell.hidden = true; loginForm.hidden = false; recoveryForm.hidden = true; setupRequired.hidden = true; authStatus.textContent = message; setAuthBusy(false); }
function showRecoveryGate(message = 'ใช้ Recovery Code เพื่อตั้งรหัสใหม่') { authScreen.hidden = false; appShell.hidden = true; loginForm.hidden = true; recoveryForm.hidden = false; setupRequired.hidden = true; authStatus.textContent = message; }
function showSetupRequired(reason) { authScreen.hidden = false; appShell.hidden = true; loginForm.hidden = true; recoveryForm.hidden = true; setupRequired.hidden = false; authStatus.textContent = reason === 'UNENROLLED' ? 'อุปกรณ์นี้ยังไม่ได้ตั้งค่ารหัส' : 'ข้อมูลรหัสอุปกรณ์ยังไม่สมบูรณ์'; }
function showApp() { authScreen.hidden = true; appShell.hidden = false; renderHomeTruth(); selectRoot(state.activeRoot || 'home'); restorePending(); }
function clearRecoveryFields() { recoveryCodeInput.value = ''; newPasswordInput.value = ''; confirmPasswordInput.value = ''; }
async function bootRuntimeGate() { authStatus.textContent = 'กำลังตรวจสถานะอุปกรณ์…'; try { const result = await runtimeGate.inspect(); if (result.status === 'LOGIN') showLoginGate(); else showSetupRequired(result.reason); } catch (error) { showSetupRequired(); authStatus.textContent = authMessage(error); } }
async function submitLogin(event) { event.preventDefault(); setAuthBusy(true); authStatus.textContent = 'กำลังตรวจรหัส…'; let unlocked = false; try { const result = await runtimeGate.login(devicePassword.value); if (result.status === 'UNLOCKED') { unlocked = true; ledgerTruth = await ledgerBridge.readLedgerTruth(); state.activeRoot = 'home'; saveState(); showApp(); } } catch (error) { if (unlocked) runtimeGate.lock(); ledgerTruth = null; const code = String(error?.message || error || ''); showLoginGate(code.startsWith('LIGHTHOUSE_LEDGER_') || code === 'RUNTIME_SESSION_LOCKED' ? 'ยังอ่านข้อมูลเงินจริงไม่ได้ กรุณาลองใหม่' : authMessage(error)); } finally { devicePassword.value = ''; setAuthBusy(false); } }
async function submitRecovery(event) { event.preventDefault(); try { await runtimeGate.resetPassword({ recoveryCode: recoveryCodeInput.value, nextPassword: newPasswordInput.value, confirmPassword: confirmPasswordInput.value }); clearRecoveryFields(); showLoginGate('ตั้งรหัสใหม่แล้ว กรุณาเข้าสู่ระบบ'); } catch (error) { clearRecoveryFields(); showRecoveryGate(authMessage(error)); } }
function lockApp() { runtimeGate.lock(); ledgerTruth = null; devicePassword.value = ''; clearRecoveryFields(); showLoginGate('LIGHTHOUSE ถูกล็อกแล้ว'); }

function selectRoot(rootId) { const allowed = ['home','chat','manual','settings']; const next = allowed.includes(rootId) ? rootId : 'home'; state.activeRoot = next; saveState(); root.querySelectorAll('.app-page').forEach((page) => { const active = page.dataset.root === next; page.hidden = !active; page.classList.toggle('active', active); }); root.querySelectorAll('.nav-item').forEach((button) => { const active = button.dataset.rootTarget === next; button.classList.toggle('active', active); button.setAttribute('aria-current', active ? 'page' : 'false'); }); pageKicker.textContent = next === 'home' ? 'วันนี้' : next === 'chat' ? 'ภาษาคน' : next === 'manual' ? 'ทำงานตรง' : 'ดูแลแอป'; if (next === 'home') renderHomeTruth(); if (next === 'chat') { ensureChatWelcome(); renderChat(); requestAnimationFrame(() => chatInput.focus({ preventScroll: true })); } if (next === 'manual') restoreManualView(); }
function addMessage(role, text, kind = role) { state.chatHistory.push({ id: `${Date.now()}-${Math.random().toString(16).slice(2)}`, role, text, kind }); state.chatHistory = state.chatHistory.slice(-80); saveState(); }
function ensureChatWelcome() { if (state.chatHistory.length) return; addMessage('app', 'พิมพ์สิ่งที่ต้องการได้เลย\nรายรับทั่วไปใช้ “จำนวนเงิน + ที่มา” เช่น “ทิป 59”\nสินค้าที่รู้จักใช้ “สินค้า + มูลค่า + จำนวน” เช่น “ขายมือถือ 566 2”\nหรือถาม “วันนี้วันที่เท่าไร”'); }
function renderChat() { ensureChatWelcome(); chatThread.replaceChildren(); for (const message of state.chatHistory) { const bubble = document.createElement('div'); bubble.className = `message ${message.kind === 'note' ? 'note' : message.role === 'user' ? 'user' : 'app'}`; bubble.textContent = message.text; chatThread.append(bubble); } renderChatActions(); if (chatSend) chatSend.disabled = !chatInput.value.trim(); requestAnimationFrame(() => { chatThread.scrollTop = chatThread.scrollHeight; }); }
function setChatActions(labels = []) { chatActions.replaceChildren(); for (const label of labels) { const button = document.createElement('button'); button.type = 'button'; button.className = 'chat-chip'; button.textContent = label; button.disabled = realIncomeCommitBusy; button.addEventListener('click', () => { void submitChatText(label); }); chatActions.append(button); } }
function renderChatActions() { const pending = state.pendingFlow; if (!pending) return setChatActions(['ทิป 59','ขายมือถือ 566','วันนี้วันที่เท่าไร']); if (pending.stage === 'CONFIRM_GENERAL_INCOME' || pending.stage === 'CONFIRM_STORE_SALE') return setChatActions(['ยืนยัน','แก้ไข','ยกเลิก']); setChatActions(['วันนี้วันที่เท่าไร','ยกเลิก']); }
function answerLocalSideQuery(text) { const normalized = text.replace(/[?？]/g,'').trim(); if (normalized !== 'วันนี้วันที่เท่าไร') return null; return `วันนี้ ${formatThaiBangkokDate(new Date())}`; }
function pendingReminder(pending) { if (!pending) return ''; if (pending.kind === 'GENERAL_INCOME') return pending.stage === 'GENERAL_INCOME_SOURCE' ? `ยังรอที่มาของรายรับ ฿${pending.amount} อยู่` : 'รายรับเดิมยังรอการยืนยันอยู่'; if (pending.kind === 'STORE_SALE') { if (pending.stage === 'STORE_SALE_VALUE') return `รายการ ${pending.productName} ยังรอมูลค่าอยู่`; if (pending.stage === 'STORE_SALE_QUANTITY') return `รายการ ${pending.productName} ยังรอจำนวนอยู่`; return `รายการขาย ${pending.productName} ยังรอการยืนยันอยู่`; } return 'ยังมีรายการเดิมค้างอยู่'; }
function resumeGeneralIncomePrompt(pending) { if (pending.stage === 'CONFIRM_GENERAL_INCOME' && pending.source) addMessage('app', `${pending.amount} บาท จาก${pending.source} — บันทึกไหม?`); else { pending.stage = 'GENERAL_INCOME_SOURCE'; addMessage('app', `ข้อมูลที่รับแล้ว: เงิน ฿${pending.amount} ✓ · ที่มา —\nรบกวนบอกเพิ่ม: ที่มาของรายรับ`); } }
function resumeStoreSalePrompt(pending) { pending.stage = storeSaleStage(pending); if (pending.stage === 'STORE_SALE_VALUE') return addMessage('app', `สินค้า ${pending.productName} ✓\nรบกวนบอกเพิ่ม: มูลค่าที่ขาย`); if (pending.stage === 'STORE_SALE_QUANTITY') return addMessage('app', `${pending.productName} · ${pending.value} บาท ✓\nรบกวนบอกเพิ่ม: จำนวนสินค้า`); addMessage('app', `${pending.productName} · ${pending.value} บาท · ${pending.quantity} ชิ้น — บันทึกไหม?`); }
function resumePendingPrompt({ afterSideQuery = false } = {}) { const pending = state.pendingFlow; if (!pending) return; if (afterSideQuery) addMessage('app', pendingReminder(pending), 'note'); if (pending.kind === 'STORE_SALE') resumeStoreSalePrompt(pending); else resumeGeneralIncomePrompt(pending); saveState(); }
function restorePending() { if (!state.pendingFlow) return; const lastText = state.chatHistory[state.chatHistory.length - 1]?.text || ''; const reminder = pendingReminder(state.pendingFlow); const alreadyVisible = lastText.includes(reminder) || lastText.includes('รบกวนบอกเพิ่ม: ที่มาของรายรับ') || lastText.includes('รบกวนบอกเพิ่ม: มูลค่าที่ขาย') || lastText.includes('รบกวนบอกเพิ่ม: จำนวนสินค้า') || lastText.includes('— บันทึกไหม?'); if (!alreadyVisible) { addMessage('app','กลับมาแล้ว — รายการที่ค้างยังอยู่','note'); resumePendingPrompt(); } if (state.activeRoot === 'chat') renderChat(); }
function cancelPending() { state.pendingFlow = null; addMessage('app','ยกเลิกรายการที่ค้างแล้ว'); saveState(); }
function refreshTruthSurfaces() { renderHomeTruth(); if (state.activeRoot === 'manual' && state.manualView) openManualTask(state.manualView); }
async function confirmGeneralIncome(pending) { if (realIncomeCommitBusy) return; ensureGeneralIncomeIdentity(pending); realIncomeCommitBusy = true; renderChatActions(); try { const result = await ledgerBridge.recordOtherIncome({ workflowId:pending.workflowId, ledgerTransactionId:pending.ledgerTransactionId, source:pending.source, amountBaht:pending.amount }); ledgerTruth = result.truth; state.pendingFlow = null; saveState(); addMessage('app', `บันทึกแล้ว ${pending.amount} บาท · ${pending.source}`); refreshTruthSurfaces(); } catch (error) { const code = String(error?.message || error || ''); addMessage('app', code === 'RUNTIME_SESSION_LOCKED' ? 'แอปถูกล็อก กรุณาเข้าสู่ระบบแล้วลองยืนยันอีกครั้ง' : 'ยังบันทึกไม่สำเร็จ รายการยังค้างอยู่ ลองอีกครั้งได้'); saveState(); } finally { realIncomeCommitBusy = false; renderChatActions(); } }
function confirmStoreSale(pending) { const product = state.products.find((item) => item.id === pending.productId); if (!product) { state.pendingFlow = null; return addMessage('app','ไม่พบสินค้านี้แล้ว — ยังไม่มีข้อมูลถูกเปลี่ยน'); } if (pending.quantity > product.stock) { pending.quantity = null; pending.stage = 'STORE_SALE_QUANTITY'; saveState(); addMessage('app', `สินค้าไม่พอ — ${product.name} เหลือ ${product.stock} ชิ้น`); return resumeStoreSalePrompt(pending); } product.stock -= pending.quantity; state.cash += pending.value; state.todayIncome += pending.value; state.transactions.push({ id:`sale-${Date.now()}-${Math.random().toString(16).slice(2)}`, type:'SALE', status:'ACTIVE', productId:product.id, productName:product.name, quantity:pending.quantity, value:pending.value, createdAt:new Date().toISOString() }); state.pendingFlow = null; addMessage('app', `บันทึกแล้ว ${product.name} · ${pending.value} บาท · ${pending.quantity} ชิ้น`); refreshTruthSurfaces(); }
async function confirmPending() { const pending = state.pendingFlow; if (!pending) return addMessage('app','รายการยังไม่พร้อมยืนยัน'); if (pending.kind === 'GENERAL_INCOME' && pending.stage === 'CONFIRM_GENERAL_INCOME' && pending.source) return confirmGeneralIncome(pending); if (pending.kind === 'STORE_SALE' && pending.stage === 'CONFIRM_STORE_SALE' && pending.value && pending.quantity) return confirmStoreSale(pending); addMessage('app','รายการยังไม่พร้อมยืนยัน'); }
function editPending() { const pending = state.pendingFlow; if (!pending) return; if (pending.kind === 'STORE_SALE') { pending.value = null; pending.quantity = null; pending.stage = 'STORE_SALE_VALUE'; } else { pending.source = null; pending.stage = 'GENERAL_INCOME_SOURCE'; } saveState(); resumePendingPrompt(); }
function normalizePendingSource(text) { return String(text || '').replace(/[“”"]/g,'').replace(/\s+/g,' ').trim().replace(/^จาก\s*/u,'').trim(); }
function parsePositiveMoney(text) { const match = String(text || '').match(/(?:฿\s*)?([0-9][0-9,]*(?:\.[0-9]{1,2})?)(?:\s*บาท)?/u); if (!match) return null; const value = Number(match[1].replaceAll(',','')); return Number.isFinite(value) && value > 0 ? value : null; }
function parsePositiveQuantity(text) { const match = String(text || '').match(/([0-9][0-9,]*)/u); if (!match) return null; const value = Number(match[1].replaceAll(',','')); return Number.isInteger(value) && value > 0 ? value : null; }
async function handlePendingInput(text) { const pending = state.pendingFlow; const clean = text.trim(); if (clean === 'ยกเลิก') return cancelPending(); if (clean === 'ยืนยัน') return confirmPending(); if (clean === 'แก้ไข') return editPending(); if (pending.kind === 'STORE_SALE') { if (pending.stage === 'STORE_SALE_VALUE') { const value = parsePositiveMoney(clean); if (!value) return addMessage('app','รบกวนบอกเพิ่ม: มูลค่าที่ขาย'); pending.value = value; pending.stage = 'STORE_SALE_QUANTITY'; saveState(); return resumeStoreSalePrompt(pending); } if (pending.stage === 'STORE_SALE_QUANTITY') { const quantity = parsePositiveQuantity(clean); if (!quantity) return addMessage('app','รบกวนบอกเพิ่ม: จำนวนสินค้า'); pending.quantity = quantity; pending.stage = 'CONFIRM_STORE_SALE'; saveState(); return resumeStoreSalePrompt(pending); } } else if (pending.stage === 'GENERAL_INCOME_SOURCE') { const source = normalizePendingSource(clean); if (!source || source.length > 80) return addMessage('app','รบกวนบอกเพิ่ม: ที่มาของรายรับ'); pending.source = source; pending.stage = 'CONFIRM_GENERAL_INCOME'; saveState(); return resumeGeneralIncomePrompt(pending); } addMessage('app','เลือก “ยืนยัน”, “แก้ไข” หรือ “ยกเลิก”'); }
function beginStoreSale(parsed) { if (parsed.ambiguous) { addMessage('app', `เจอสินค้าที่เป็นไปได้มากกว่าหนึ่งรายการ: ${parsed.candidates.map((candidate)=>candidate.productName).join(' / ')}\nรบกวนพิมพ์ชื่อสินค้าให้ชัดขึ้น`); return true; } state.pendingFlow = { kind:'STORE_SALE', stage:'STORE_SALE_VALUE', productId:parsed.productId, productName:parsed.productName, value:parsed.value, quantity:parsed.quantity }; state.pendingFlow.stage = storeSaleStage(state.pendingFlow); saveState(); resumePendingPrompt(); return true; }
async function handleChatInput(text) { const clean = text.trim(); if (!clean) return; const sideAnswer = answerLocalSideQuery(clean); if (sideAnswer) { addMessage('app',sideAnswer); if (state.pendingFlow) resumePendingPrompt({ afterSideQuery:true }); return; } if (state.pendingFlow) return handlePendingInput(clean); const storeSale = parseStoreSale(clean, state.products); if (storeSale) return beginStoreSale(storeSale); const parsed = parseGeneralIncome(clean); if (parsed) { state.pendingFlow = { kind:'GENERAL_INCOME', stage:parsed.source ? 'CONFIRM_GENERAL_INCOME' : 'GENERAL_INCOME_SOURCE', amount:parsed.amount, source:parsed.source, workflowId:null, ledgerTransactionId:null }; saveState(); return resumePendingPrompt(); } addMessage('app','ตอนนี้สนามนี้รองรับรายรับทั่วไปแบบ “จำนวนเงิน + ที่มา”, การขายสินค้าที่รู้จักแบบ “สินค้า + มูลค่า + จำนวน” และคำถาม “วันนี้วันที่เท่าไร”'); }
async function submitChatText(text) { const clean = String(text || '').trim(); if (!clean) return; addMessage('user',clean); renderChat(); await handleChatInput(clean); renderChat(); }

const manualContent = { finance:{title:'การเงิน',intro:'เห็นเงินจริง การเคลื่อนไหว ภาระ และเป้าหมายในภาพเดียวกัน',rows:[]}, store:{title:'ร้านค้า',intro:'สรุปการขายและสต็อกจากข้อมูลก้อนเดียวกับแชต',rows:[]}, ride:{title:'งานวิ่ง',intro:'ดูรอบงาน รายได้ และค่าใช้จ่ายที่เกี่ยวกับการวิ่งโดยตรง',rows:[['สถานะวันนี้','ยังไม่เริ่มรอบ'],['รายได้วันนี้','฿0'],['ค่าใช้จ่ายวันนี้','฿0']]}, calendar:{title:'ปฏิทิน',intro:'ดูสิ่งที่ต้องทำตามวัน โดยรายละเอียดอยู่ในบ้านเดียวกัน',rows:[]}, ledger:{title:'รายการทั้งหมด',intro:'ย้อนดูรายการเงินจริงจาก Ledger',rows:[]} };
function showManualHub() { state.manualView = null; manualHub.hidden = false; manualDetail.hidden = true; saveState(); }
function makeDetailHero(data) { const hero=document.createElement('div'); hero.className='detail-hero'; const title=document.createElement('h2'); title.textContent=data.title; const intro=document.createElement('p'); intro.textContent=data.intro; hero.append(title,intro); return hero; }
function makeDetailRow(label,value) { const row=document.createElement('div'); row.className='detail-row'; const left=document.createElement('span'); left.textContent=label; const right=document.createElement('strong'); right.textContent=value; row.append(left,right); return row; }
function renderStaticDetail(data, rows=data.rows) { const list=document.createElement('div'); list.className='detail-list'; for (const [label,value] of rows) list.append(makeDetailRow(label,value)); manualDetailContent.append(makeDetailHero(data),list); }
function renderFinanceDetail() { const data = manualContent.finance; const snapshot = financeSnapshot(); const rows = [['เงินจริง', snapshot ? formatSatang(snapshot.cashSatang) : '—'], ['เงินเข้าวันนี้', snapshot ? formatSatang(snapshot.todayIncomeSatang) : '—'], ['เงินออกวันนี้', snapshot ? formatSatang(snapshot.todayExpenseSatang) : '—'], ['สุทธิ', snapshot ? `${snapshot.netSatang >= 0 ? '+' : '-'}${formatSatang(Math.abs(snapshot.netSatang))}` : '—'], ['ภาระใกล้สุด', 'ยังไม่เชื่อมข้อมูลจริง'], ['คาดว่าจะเข้า', '—']]; renderStaticDetail(data, rows); }
function renderStoreDetail() { const data=manualContent.store; const list=document.createElement('div'); list.className='detail-list'; const activeSales=state.transactions.filter((transaction)=>transaction.type==='SALE'&&transaction.status==='ACTIVE'); const salesValue=activeSales.reduce((total,transaction)=>total+Number(transaction.value||0),0); list.append(makeDetailRow('ยอดขายที่บันทึก',`${activeSales.length} รายการ · ${formatBaht(salesValue)}`)); for (const product of state.products) list.append(makeDetailRow(product.name,`เหลือ ${product.stock} ชิ้น`)); manualDetailContent.append(makeDetailHero(data),list); }
function renderCalendarDetail() { const data=manualContent.calendar; const openObligations=state.obligations.filter((obligation)=>obligation.status==='OPEN'); const rows=openObligations.length ? [['ภาระที่กำลังมา',`${openObligations.length} รายการ`],...openObligations.map((obligation)=>[obligation.dueLabel,`${obligation.title} · ${formatBaht(obligation.amount)}`])] : [['กำหนดใกล้','ยังไม่มีรายการ']]; renderStaticDetail(data,rows); }
function transactionLabel(transaction) { if (transaction.type==='SALE') return transaction.productName||'ขายสินค้า'; if (transaction.type==='INCOME') return transaction.source||'รายรับ'; if (transaction.type==='REVERSAL') return `ย้อนรายการ · ${transaction.productName||'สินค้า'}`; return 'รายการ'; }
function transactionValue(transaction) { const raw=Number(transaction.value||0); if (transaction.type==='REVERSAL') return `-${formatBaht(Math.abs(raw))}`; return `+${formatBaht(Math.abs(raw))}`; }
function ledgerHistoryValue(transaction) { const direction = transaction.direction === 'OUT' ? '-' : '+'; return `${direction}${formatSatang(transaction.amountSatang)}`; }
function ledgerHistoryDetail(transaction) { if (transaction.detail === 'IN:OTHER_INCOME') return 'รายรับทั่วไป'; return transaction.direction === 'IN' ? 'เงินเข้า' : 'เงินออก'; }
function renderHistoryDetail() { const data=manualContent.ledger; const list=document.createElement('div'); list.className='detail-list history-list'; const transactions=ledgerTruth?.transactions || []; if (!transactions.length) list.append(makeDetailRow('ประวัติ','ยังไม่มีรายการ')); for (const transaction of transactions) { const row=document.createElement('div'); row.className='detail-row history-row'; const copy=document.createElement('span'); copy.className='history-copy'; const title=document.createElement('strong'); title.textContent=transaction.title || 'รายการเงิน'; const detail=document.createElement('small'); detail.textContent=ledgerHistoryDetail(transaction); copy.append(title,detail); const value=document.createElement('strong'); value.textContent=ledgerHistoryValue(transaction); row.append(copy,value); list.append(row); } manualDetailContent.append(makeDetailHero(data),list); }
function openManualTask(taskId) { const data=manualContent[taskId]; if (!data) return; state.manualView=taskId; saveState(); manualHub.hidden=true; manualDetail.hidden=false; manualDetailContent.replaceChildren(); if (taskId==='finance') return renderFinanceDetail(); if (taskId==='store') return renderStoreDetail(); if (taskId==='calendar') return renderCalendarDetail(); if (taskId==='ledger') return renderHistoryDetail(); renderStaticDetail(data); }
function restoreManualView() { if (state.manualView && manualContent[state.manualView]) openManualTask(state.manualView); else showManualHub(); }
function confirmSaleReversal(saleId) { const sale=state.transactions.find((transaction)=>transaction.id===saleId&&transaction.type==='SALE'); if (!sale||sale.status!=='ACTIVE') return false; const alreadyReversed=state.transactions.some((transaction)=>transaction.type==='REVERSAL'&&transaction.reversalOf===sale.id); if (alreadyReversed) return false; const product=state.products.find((item)=>item.id===sale.productId); if (product) product.stock+=Number(sale.quantity||0); state.cash-=Number(sale.value||0); state.todayIncome-=Number(sale.value||0); sale.status='CANCELLED'; sale.cancelledAt=new Date().toISOString(); state.transactions.push({id:`reversal-${Date.now()}-${Math.random().toString(16).slice(2)}`,type:'REVERSAL',status:'ACTIVE',reversalOf:sale.id,productId:sale.productId,productName:sale.productName,quantity:sale.quantity,value:-Number(sale.value||0),createdAt:new Date().toISOString()}); saveState(); refreshTruthSurfaces(); return true; }
function ensureSaleReversalDialog() { let dialog=root.querySelector('#sale-reversal-dialog'); if (dialog) return dialog; dialog=document.createElement('dialog'); dialog.id='sale-reversal-dialog'; dialog.className='confirm-dialog'; dialog.innerHTML='<form method="dialog"><div class="dialog-beacon" aria-hidden="true">✦</div><h2>ยกเลิกรายการ?</h2><p>ยอดเงินและจำนวนสินค้าจะถูกย้อนกลับ และประวัติเดิมจะยังอยู่</p><div class="dialog-actions"><button value="cancel" class="secondary-button">ยังไม่ยกเลิก</button><button value="confirm" class="danger-button" data-confirm-sale-reversal>ยืนยันยกเลิกรายการ</button></div></form>'; dialog.querySelector('[data-confirm-sale-reversal]').addEventListener('click',()=>{ if (pendingReversalSaleId) confirmSaleReversal(pendingReversalSaleId); pendingReversalSaleId=null; }); dialog.addEventListener('close',()=>{pendingReversalSaleId=null;}); root.append(dialog); return dialog; }
function requestSaleReversal(saleId) { const sale=state.transactions.find((transaction)=>transaction.id===saleId&&transaction.type==='SALE'&&transaction.status==='ACTIVE'); if (!sale) return; pendingReversalSaleId=saleId; const dialog=ensureSaleReversalDialog(); if (typeof dialog.showModal==='function') dialog.showModal(); else if (window.confirm(`ยกเลิกรายการ ${sale.productName}?`)) { confirmSaleReversal(saleId); pendingReversalSaleId=null; } }

loginForm.addEventListener('submit', submitLogin);
recoveryForm.addEventListener('submit', submitRecovery);
showRecoveryButton.addEventListener('click', () => { devicePassword.value = ''; showRecoveryGate(); });
cancelRecoveryButton.addEventListener('click', () => { clearRecoveryFields(); showLoginGate(); });
lockAppButton.addEventListener('click', lockApp);
window.addEventListener('pagehide', () => { runtimeGate.lock(); });
root.querySelectorAll('[data-root-target]').forEach((button)=>button.addEventListener('click',()=>selectRoot(button.dataset.rootTarget)));
root.querySelectorAll('[data-task]').forEach((button)=>button.addEventListener('click',()=>openManualTask(button.dataset.task)));
root.querySelector('#manual-back').addEventListener('click',showManualHub);
chatForm.addEventListener('submit', async event => { event.preventDefault(); const value = chatInput.value; chatInput.value = ''; if (chatSend) chatSend.disabled = true; await submitChatText(value); chatInput.focus({ preventScroll:true }); });
chatInput.addEventListener('input',()=>{ chatInput.style.height='auto'; chatInput.style.height=`${Math.min(chatInput.scrollHeight,118)}px`; if (chatSend) chatSend.disabled=!chatInput.value.trim(); });
chatInput.addEventListener('keydown',(event)=>{ if (event.key==='Enter'&&!event.shiftKey){ event.preventDefault(); chatForm.requestSubmit(); } });
root.querySelector('#reset-demo').addEventListener('click',()=>{ if (typeof resetDialog.showModal==='function') resetDialog.showModal(); else if (window.confirm('เริ่มสนามใหม่และล้างข้อมูลทดลอง?')) resetDemoState(); });
root.querySelector('#confirm-reset').addEventListener('click',()=>window.setTimeout(resetDemoState,0));

homeDate.textContent = formatThaiBangkokDate(new Date());
renderHomeTruth();
restoreManualView();
void AMBIGUITY_LOCK;

const visualViewport = window.visualViewport;
let keyboardBaselineHeight = visualViewport?.height || window.innerHeight;
function syncKeyboardViewport() { const viewportHeight=visualViewport?.height||window.innerHeight; const inputFocused=document.activeElement===chatInput; if (!inputFocused) { keyboardBaselineHeight=viewportHeight; root.classList.toggle('keyboard-open',false); return; } const keyboardOpen=keyboardBaselineHeight-viewportHeight>120; root.classList.toggle('keyboard-open',keyboardOpen); }
if (visualViewport) { visualViewport.addEventListener('resize',syncKeyboardViewport); visualViewport.addEventListener('scroll',syncKeyboardViewport); }
window.addEventListener('resize',syncKeyboardViewport);
chatInput.addEventListener('focus',syncKeyboardViewport);
chatInput.addEventListener('blur',()=>{ root.classList.toggle('keyboard-open',false); keyboardBaselineHeight=visualViewport?.height||window.innerHeight; });
syncKeyboardViewport();

await bootRuntimeGate();