import { openGreenfieldRuntime, openGreenfieldRuntimeWithDevicePin, enrollGreenfieldDeviceUnlock } from '../greenfield/runtime.mjs';
import { resolveCalendarAction } from '../greenfield/action-contract.mjs';
import { parseBahtToSatang, formatSatang, makeId, parseInstallments } from './ui-model.mjs';
import { recordsForDomain, dateKey, deriveTimeState, isCalendarActionableStatus, projectMakeMoney, projectStore, suggestDailyGoal, projectFinance, projectCashFlowSeries, buildMonthGrid } from './product-model.mjs';
import { createRideUi } from './ride-ui.mjs';
import { createHomeUi } from './home-ui.mjs';
import { createStoreUi } from './store-ui.mjs';
import { createFinanceUi } from './finance-ui.mjs';
import { hydrateIcons } from './icons.mjs';

const $=id=>document.getElementById(id);
let runtime=null,state=null,activeArea='home',activeStoreView='overview';
let selectedCalendarDate=dateKey(new Date()),monthCursor=monthFromDate(selectedCalendarDate),editingCalendarRecordId=null;
const AREA_LABEL=Object.freeze({home:'หน้าหลัก',store:'ร้านค้า',ride:'วิ่งงาน',finance:'การเงิน'});
const STORE_VIEWS=new Set(['overview','receivables','stock-movements','history']);
function status(message,error=false,gate=false){const node=$(gate?'gateStatus':'appStatus');node.textContent=message||'';node.classList.toggle('error',error);}
function devicePin(){const value=$('devicePin').value;if(value.length<6)throw new Error('รหัสเข้าแอปต้องมีอย่างน้อย 6 ตัวอักษร');return value;}
function recoveryPassphrase(){const value=$('recoveryPassphrase').value;if(value.length<12)throw new Error('รหัสกู้คืนต้องมีอย่างน้อย 12 ตัวอักษร');return value;}
async function jsonFile(input){const file=input.files?.[0];if(!file)throw new Error('เลือกไฟล์ก่อน');return JSON.parse(await file.text());}
async function ensureRecoveryRuntime(){runtime?.close();runtime=await openGreenfieldRuntime({passphrase:recoveryPassphrase()});return runtime;}
function monthFromDate(key){const match=/^(\d{4})-(\d{2})/.exec(String(key||''));const now=new Date();return match?{year:Number(match[1]),monthIndex:Number(match[2])-1}:{year:now.getFullYear(),monthIndex:now.getMonth()};}
function shiftDate(key,days){const [y,m,d]=key.split('-').map(Number);const date=new Date(Date.UTC(y,m-1,d+days));return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`;}
function todayKey(){return dateKey(new Date());}
function dailyIncomeHistory(currentState,today,days=7){const result=[];for(let offset=days;offset>=1;offset-=1){const date=shiftDate(today,-offset);result.push({date,amountSatang:projectMakeMoney(currentState,date).combinedSatang});}return result;}
function openObligationQueues(currentState){return recordsForDomain(currentState,'CALENDAR').filter(record=>['PAY_OBLIGATION','PAY_OBLIGATION_INSTALLMENT'].includes(record.type)&&!['COMPLETED','CANCELLED'].includes(record.status));}
async function ensureTodayGoal(){const today=todayKey();const projection=runtime.project();const suggestion=suggestDailyGoal({dailyIncome:dailyIncomeHistory(state,today),balanceSatang:projection.ledgerBalanceSatang,nearObligations:openObligationQueues(state),today});const result=await runtime.ensureDailyGoal({date:today,suggestedSatang:suggestion.goalSatang});state=result.state;return result.goal;}
async function openWorkspace(){if(!state)throw new Error('ยังไม่มีฐาน METROPOLIS');await ensureTodayGoal();$('gate').classList.add('hidden');$('workspace').classList.remove('hidden');$('commandNav').classList.remove('hidden');$('runtimeBadge').textContent='READY';selectedCalendarDate||=todayKey();monthCursor=monthFromDate(selectedCalendarDate);hydrateIcons();activateArea(activeArea);render();}
async function refresh(message=''){state=await runtime.readState();if(!state)throw new Error('ยังไม่มีฐาน METROPOLIS');render();if(message)status(message);}
async function run(method,input,message='บันทึกและอ่านกลับแล้ว'){try{await runtime[method](input);await refresh(message);}catch(error){status(error.message,true);}}
function bindForm(id,handler){$(id).addEventListener('submit',async event=>{event.preventDefault();try{await handler(new FormData(event.currentTarget),event.currentTarget);}catch(error){status(error.message,true);}});}
function installSaleCostUi(){const form=$('saleForm');if(!form||form.elements.namedItem('storeCost'))return;const costLabel=document.createElement('label');costLabel.textContent='ต้นทุนร้านค้า (บาท) ';const costInput=document.createElement('input');costInput.name='storeCost';costInput.inputMode='decimal';costInput.value='0';costInput.placeholder='ค่าส่ง / น้ำมัน / แพ็กเกจ / ค่าเสื่อม';costLabel.append(costInput);const net=document.createElement('p');net.className='muted';const netValue=document.createElement('strong');netValue.textContent='0 บาท';net.append('รายได้สุทธิ ',netValue);const due=form.elements.namedItem('dueDate')?.closest?.('label');if(due){due.before(costLabel,net);}else{form.append(costLabel,net);}const received=form.elements.namedItem('received');const update=()=>{try{const receivedSatang=parseBahtToSatang(received?.value||'0');const costSatang=parseBahtToSatang(costInput.value||'0');netValue.textContent=`${formatSatang(receivedSatang-costSatang)} บาท`;}catch{netValue.textContent='—';}};received?.addEventListener('input',update);costInput.addEventListener('input',update);update();}
installSaleCostUi();
function setStoreView(view='overview'){activeStoreView=STORE_VIEWS.has(view)?view:'overview';document.querySelectorAll('[data-store-view]').forEach(node=>node.classList.toggle('hidden',node.dataset.storeView!==activeStoreView));}
function normalizeAreaRoute(target={}){const requested=String(target.area||'HOME').toUpperCase();if(requested==='SYSTEM')return{area:'system',focus:target.focus||null};if(requested==='MAKE_MONEY')return{area:target.focus==='ride'?'ride':target.focus==='store'?'store':'home',focus:target.focus||null};if(requested==='CALENDAR')return{area:'finance',focus:'schedule'};const area=({HOME:'home',STORE:'store',RIDE:'ride',FINANCE:'finance'})[requested]||String(target.area||'').toLowerCase();return{area:AREA_LABEL[area]?area:'home',focus:target.focus||null};}
function activateArea(area){if(!AREA_LABEL[area])area='home';activeArea=area;$('workspace').dataset.activeArea=area;document.documentElement.dataset.activeArea=area;document.querySelectorAll('.command-nav-btn[data-command-destination]').forEach(button=>{const active=button.dataset.commandDestination===area;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});const homeBubble=$('homeBubble');const homeActive=area==='home';homeBubble.classList.toggle('active',homeActive);if(homeActive)homeBubble.setAttribute('aria-current','page');else homeBubble.removeAttribute('aria-current');document.querySelectorAll('[data-area-page]').forEach(page=>page.classList.toggle('active',page.dataset.areaPage===area));if(area==='store')setStoreView('overview');if(area==='ride')rideUi.setRideView('overview');}
function openSettings(){if(runtime&&state)renderSystem(buildContext());const dialog=$('settingsDialog');if(!dialog.open)dialog.showModal();}
function focusRouteTarget(focus){const node=focus==='schedule'?$('financeSchedule'):focus==='near-term-pressure'?$('financePressure'):null;if(!node)return;requestAnimationFrame(()=>{node.focus?.({preventScroll:true});node.scrollIntoView({block:'start',behavior:'smooth'});});}
function routeTo(target={}){const route=normalizeAreaRoute(target);if(route.area==='system'){openSettings();return;}if(target.date){selectedCalendarDate=target.date;monthCursor=monthFromDate(target.date);}activateArea(route.area);render();if(route.focus)focusRouteTarget(route.focus);}
function numberText(value){return `${formatSatang(Number(value||0))}`;}
function bahtText(value){return `${numberText(value)} บาท`;}
function recordDateLabel(record){const key=dateKey(record?.dueDate||record?.createdAt||record?.date||record?.updatedAt);if(!key)return '';return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${key}T12:00:00+07:00`));}
const TYPE_LABEL=Object.freeze({SALE:'ขายสินค้า',PURCHASE:'รับสินค้าเข้า',STOCK_WITHDRAWAL:'เบิกสินค้า',STOCK_ADJUSTMENT:'ปรับสต็อก',TRANSACTION:'เงินเข้า–ออก',OBLIGATION:'ภาระ',ROUND:'รอบวิ่ง',JOB:'งานวิ่ง',EXPENSE:'ค่าใช้จ่ายวิ่ง',CREDIT_WITHDRAWAL:'เบิกเครดิต',RECEIVE_CUSTOMER_PAYMENT:'รับเงินลูกค้า',PAY_OBLIGATION:'จ่ายภาระ',PAY_OBLIGATION_INSTALLMENT:'จ่ายงวด',PURCHASE_RETURN_WINDOW:'กำหนดคืนสินค้า'});
function simpleItem(record,{amountField='amountSatang'}={}){const item=document.createElement('article');item.className='item';const head=document.createElement('div');head.className='item-head';const title=document.createElement('b');title.textContent=record.title||TYPE_LABEL[record.type]||'รายการ';const statusNode=document.createElement('small');statusNode.textContent=record.status||'';head.append(title,statusNode);const meta=document.createElement('div');meta.className='muted';const amount=Number(record[amountField]);const pieces=[TYPE_LABEL[record.type]||record.type||''];if(Number.isSafeInteger(amount)&&amount!==0)pieces.push(bahtText(amount));const date=recordDateLabel(record);if(date)pieces.push(date);meta.textContent=pieces.filter(Boolean).join(' · ');item.append(head,meta);return item;}
const rideUi=createRideUi({getRuntime:()=>runtime,getState:()=>state,run,status,bindForm,bahtText,simpleItem});
const homeUi=createHomeUi({getById:$,bahtText,numberText,routeTo});
const storeUi=createStoreUi({getById:$,getState:()=>state,getActiveStoreView:()=>activeStoreView,bahtText,simpleItem,setStoreView});
const financeUi=createFinanceUi({getById:$,numberText,bahtText,simpleItem,routeTo});
function calendarRecordById(recordId){return recordsForDomain(state,'CALENDAR').find(record=>record.recordId===recordId)||null;}
function openCalendarEdit(record){editingCalendarRecordId=record.recordId;$('calendarEditLabel').textContent=record.title||TYPE_LABEL[record.type]||'รายการ';$('calendarEditDueDate').value=dateKey(record.dueDate||record.date||record.scheduledDate);const dialog=$('calendarEditDialog');if(!dialog.open)dialog.showModal();}
function actionReasonText(reason){return ({SOURCE_NOT_FOUND:'ต้องตรวจสอบแหล่งต้นทางก่อน',SOURCE_AMBIGUOUS:'ต้องตรวจสอบ · พบแหล่งต้นทางมากกว่า 1 รายการ',SOURCE_OWNER_CONFLICT:'ต้องตรวจสอบเจ้าของข้อมูล',SOURCE_RELATION_CONFLICT:'ต้องตรวจสอบความสัมพันธ์ของรายการ',SOURCE_AMOUNT_INVALID:'ต้องตรวจสอบยอดคงเหลือ',ACTION_NOT_OPEN:'รายการนี้ยังทำ action ไม่ได้'})[reason]||'ต้องตรวจสอบรายการก่อนดำเนินการ';}
function calendarActionItem(record){const item=simpleItem(record);const timeState=deriveTimeState(record,todayKey());const meta=document.createElement('small');meta.className='muted';meta.dataset.timeState=timeState;meta.textContent=timeState==='OVERDUE'?'เลยกำหนด':timeState==='TODAY'?'วันนี้':timeState==='NEAR'?'ใกล้ถึง':'';if(meta.textContent)item.append(meta);if(!isCalendarActionableStatus(record.status))return item;const actions=document.createElement('div');actions.className='item-actions';const action=resolveCalendarAction(state,record);if(action.available&&['PAY_OBLIGATION','RECEIVE_CUSTOMER_PAYMENT'].includes(action.kind)){const input=document.createElement('input');input.inputMode='decimal';input.value=formatSatang(Number(action.maxAmountSatang||0));input.setAttribute('aria-label','จำนวนเงิน');const pay=document.createElement('button');pay.textContent=action.kind==='RECEIVE_CUSTOMER_PAYMENT'?'รับเงิน':'ชำระ';pay.addEventListener('click',async()=>{try{const amountSatang=parseBahtToSatang(input.value);if(amountSatang>action.maxAmountSatang)throw new Error('จำนวนเงินเกินยอดคงเหลือ');await runtime[action.method]({workflowId:makeId('WF-PAY'),queueId:action.queueId,ledgerTransactionId:makeId('TX'),amountSatang});await refresh('บันทึกเงินจริงและอัปเดตคิวแล้ว');}catch(error){status(error.message,true);}});actions.append(input,pay);}else if(action.available&&action.kind==='COMPLETE_CALENDAR'){const complete=document.createElement('button');complete.textContent='เสร็จ';complete.addEventListener('click',()=>run('calendarStatus',{workflowId:makeId('WF-CAL'),queueId:record.recordId,status:'COMPLETED'},'อัปเดตสถานะแล้ว'));actions.append(complete);}else if(!action.available){const verify=document.createElement('small');verify.className='truth-warning-text';verify.textContent=actionReasonText(action.reason);actions.append(verify);}const edit=document.createElement('button');edit.className='secondary';edit.textContent='แก้ไขวัน/คิว';edit.addEventListener('click',()=>openCalendarEdit(record));actions.append(edit);item.append(actions);return item;}
function renderCalendar(){if(!state||!runtime)return;const records=recordsForDomain(state,'CALENDAR');const today=todayKey();const statuses=records.map(record=>deriveTimeState(record,today));$('calOverdue').textContent=statuses.filter(value=>value==='OVERDUE').length;$('calNear').textContent=statuses.filter(value=>value==='TODAY'||value==='NEAR').length;const finance=projectFinance(state,runtime.project().ledgerBalanceSatang,today);$('calCollision').textContent=finance.collisionDates.length;const grid=buildMonthGrid({year:monthCursor.year,monthIndex:monthCursor.monthIndex,calendarRecords:records,today});const labelDate=new Date(Date.UTC(monthCursor.year,monthCursor.monthIndex,15));$('monthLabel').textContent=new Intl.DateTimeFormat('th-TH',{month:'long',year:'numeric',timeZone:'UTC'}).format(labelDate);const node=$('monthGrid');node.textContent='';for(const cell of grid.cells){const button=document.createElement('button');button.className='day-cell';if(!cell.inMonth)button.classList.add('outside');if(cell.isToday)button.classList.add('today');if(cell.date===selectedCalendarDate)button.classList.add('selected');if(cell.state)button.classList.add(`state-${cell.state.toLowerCase()}`);if(cell.collision)button.classList.add('collision');button.setAttribute('aria-label',cell.date);const day=document.createElement('span');day.textContent=cell.day;button.append(day);if(cell.count){const count=document.createElement('span');count.className='day-count';count.textContent=cell.count;button.append(count);}button.addEventListener('click',()=>{selectedCalendarDate=cell.date;renderCalendar();});node.append(button);}const selected=selectedCalendarDate||today;$('selectedDayTitle').textContent=new Intl.DateTimeFormat('th-TH',{weekday:'short',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${selected}T12:00:00+07:00`));const filter=$('calendarFilter').value;let selectedRecords=records.filter(record=>dateKey(record.dueDate||record.date||record.scheduledDate)===selected);if(filter==='ACTIVE')selectedRecords=selectedRecords.filter(record=>!['COMPLETED','CANCELLED'].includes(record.status));if(filter==='COMPLETED')selectedRecords=selectedRecords.filter(record=>record.status==='COMPLETED');if(filter==='CANCELLED')selectedRecords=selectedRecords.filter(record=>record.status==='CANCELLED');const list=$('calendarList');list.textContent='';selectedRecords.sort((a,b)=>String(a.title||'').localeCompare(String(b.title||''),'th'));for(const record of selectedRecords)list.append(calendarActionItem(record));if(!selectedRecords.length)list.textContent='ไม่มีรายการในวันที่เลือก';}
function renderSystem(context){const diagnostics=runtime.diagnostics();$('systemRevision').textContent=state.revision;$('systemSchema').textContent=diagnostics.schema;$('systemDatabase').textContent=diagnostics.database;$('systemCoordination').textContent=diagnostics.coordination.mode==='WEB_LOCKS'?'ล็อกข้ามบริบท':'คิวภายในหน้า';$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);$('systemDbState').textContent=context.finance?'พร้อมใช้':'ตรวจสอบ';}
function buildContext(){const today=todayKey();const projection=runtime.project();const storeRecords=recordsForDomain(state,'STORE');const ledgerRecords=recordsForDomain(state,'LEDGER');const calendarRecords=recordsForDomain(state,'CALENDAR');const rideRecords=recordsForDomain(state,'RIDE');const money=projectMakeMoney(state,today);const store=projectStore(state,today);const finance=projectFinance(state,projection.ledgerBalanceSatang,today);const cashFlow=projectCashFlowSeries(state,today,7);const goal=state.meta?.dailyGoals?.[today]||{date:today,goalSatang:0,source:'AUTO'};return{today,projection,storeRecords,ledgerRecords,calendarRecords,rideRecords,money,store,finance,cashFlow,goal};}
function render(){if(!runtime||!state)return;const context=buildContext();homeUi.renderHome(context);storeUi.renderStore(context);rideUi.renderRide(context);financeUi.renderFinance(context);renderCalendar();renderSystem(context);}

$('unlockBtn').addEventListener('click',async()=>{try{runtime?.close();runtime=await openGreenfieldRuntimeWithDevicePin({pin:devicePin()});state=await runtime.readState();if(!state)throw new Error('ยังไม่พบฐาน METROPOLIS');await openWorkspace();}catch(error){const message=error.message==='DEVICE_UNLOCK_NOT_ENROLLED'?'เครื่องนี้ยังไม่ได้ตั้งรหัสเข้าแอป — เปิด “กู้คืนการเข้าถึง” เพื่อตั้งครั้งแรก':error.message;status(message,true,true);}});
$('enrollDeviceBtn').addEventListener('click',async()=>{try{runtime?.close();runtime=null;await enrollGreenfieldDeviceUnlock({vaultPassphrase:recoveryPassphrase(),pin:devicePin()});runtime=await openGreenfieldRuntimeWithDevicePin({pin:devicePin()});state=await runtime.readState();if(!state)throw new Error('ยังไม่พบฐาน METROPOLIS');$('recoveryPassphrase').value='';await openWorkspace();status('ตั้งรหัสเข้าแอปบนเครื่องนี้แล้ว');}catch(error){status(error.message,true,true);}});
$('importEvidenceBtn').addEventListener('click',async()=>{try{const evidence=await jsonFile($('evidenceFile'));await ensureRecoveryRuntime();const result=await runtime.initializeFromEvidence(evidence,{expectedPackageId:'FLOW-1786527289637',expectedRevision:28});state=result.state;await openWorkspace();status(`นำเข้า Evidence ผ่าน · revision ${state.revision}`);}catch(error){status(error.message,true,true);}});
$('restoreBtn').addEventListener('click',async()=>{try{const backup=await jsonFile($('restoreFile'));await ensureRecoveryRuntime();const result=await runtime.restoreBackup(backup);state=result.state;await openWorkspace();status('กู้คืน Backup และตรวจอ่านกลับแล้ว');}catch(error){status(error.message,true,true);}});
document.querySelectorAll('.command-nav-btn[data-command-destination],#homeBubble[data-command-destination]').forEach(button=>button.addEventListener('click',()=>activateArea(button.dataset.commandDestination)));
document.querySelectorAll('[data-store-open]').forEach(button=>button.addEventListener('click',()=>setStoreView(button.dataset.storeOpen)));
rideUi.bindRide();
$('settingsBtn').addEventListener('click',openSettings);
$('settingsCloseBtn').addEventListener('click',()=>{$('settingsDialog').close();});
$('calendarEditCloseBtn').addEventListener('click',()=>{$('calendarEditDialog').close();editingCalendarRecordId=null;});
$('calendarRescheduleBtn').addEventListener('click',async()=>{const record=calendarRecordById(editingCalendarRecordId);if(!record)return status('ไม่พบรายการปฏิทิน',true);try{const dueDate=$('calendarEditDueDate').value;await runtime.calendarReschedule({workflowId:makeId('WF-CAL-MOVE'),queueId:record.recordId,dueDate});selectedCalendarDate=dueDate;monthCursor=monthFromDate(dueDate);$('calendarEditDialog').close();editingCalendarRecordId=null;await refresh('เลื่อนวันครบกำหนดแล้ว');}catch(error){status(error.message,true);}});
$('calendarCancelOpenBtn').addEventListener('click',()=>{const record=calendarRecordById(editingCalendarRecordId);if(!record)return status('ไม่พบรายการปฏิทิน',true);$('calendarCancelCopy').textContent=`ยืนยันยกเลิก “${record.title||TYPE_LABEL[record.type]||'รายการ'}” โดยไม่สร้างหรือย้อนเงินจริง`;$('calendarEditDialog').close();$('calendarCancelDialog').showModal();$('calendarCancelBackBtn').focus();});
$('calendarCancelBackBtn').addEventListener('click',()=>{$('calendarCancelDialog').close();const record=calendarRecordById(editingCalendarRecordId);if(record&&isCalendarActionableStatus(record.status))openCalendarEdit(record);});
$('calendarCancelConfirmBtn').addEventListener('click',async()=>{const record=calendarRecordById(editingCalendarRecordId);if(!record)return status('ไม่พบรายการปฏิทิน',true);try{await runtime.calendarStatus({workflowId:makeId('WF-CAL-CANCEL'),queueId:record.recordId,status:'CANCELLED'});$('calendarCancelDialog').close();editingCalendarRecordId=null;await refresh('ยกเลิกรายการแล้ว');}catch(error){status(error.message,true);}});
bindForm('goalForm',async data=>{const result=await runtime.overrideDailyGoal({date:todayKey(),goalSatang:parseBahtToSatang(data.get('goal'))});state=result.state;render();status('ปรับเป้าวันนี้แล้ว');});
bindForm('saleForm',data=>{const amount=parseBahtToSatang(data.get('amount'));const received=parseBahtToSatang(data.get('received')||'0');const storeCost=parseBahtToSatang(data.get('storeCost')||'0');const dueDate=data.get('dueDate')||undefined;if(received<amount&&!dueDate)throw new Error('ยอดยังรับไม่ครบ — ใส่วันครบกำหนดเพื่อสร้างคิวรับเงิน');return run('sale',{workflowId:makeId('WF-SALE'),saleId:makeId('SALE'),ledgerTransactionId:received>0?makeId('TX'):undefined,calendarQueueId:received<amount?makeId('Q'):undefined,title:data.get('title'),amountSatang:amount,quantity:Number(data.get('quantity')),receivedSatang:received,storeCostSatang:storeCost,dueDate});});
bindForm('purchaseForm',data=>{const due=data.get('returnDueDate')||null;return run('purchase',{workflowId:makeId('WF-BUY'),purchaseId:makeId('BUY'),ledgerTransactionId:makeId('TX'),returnQueueId:due?makeId('Q'):null,title:data.get('title'),amountSatang:parseBahtToSatang(data.get('amount')),quantity:Number(data.get('quantity')),returnDueDate:due});});
bindForm('withdrawForm',data=>run('stockWithdrawal',{workflowId:makeId('WF-WD'),recordId:makeId('WD'),title:data.get('title'),quantity:Number(data.get('quantity'))}));
bindForm('adjustForm',data=>run('stockAdjustment',{workflowId:makeId('WF-ADJ'),recordId:makeId('ADJ'),title:data.get('title'),deltaQuantity:Number(data.get('delta')),reason:data.get('reason')}));
bindForm('incomeForm',data=>run('otherIncome',{workflowId:makeId('WF-IN'),ledgerTransactionId:makeId('TX'),title:data.get('title'),amountSatang:parseBahtToSatang(data.get('amount'))}));
bindForm('expenseForm',data=>run('expense',{workflowId:makeId('WF-OUT'),ledgerTransactionId:makeId('TX'),title:data.get('title'),amountSatang:parseBahtToSatang(data.get('amount'))}));
bindForm('obligationForm',data=>{const installments=parseInstallments(data.get('installments')).map(item=>({...item,queueId:makeId('Q')}));return run('obligation',{workflowId:makeId('WF-OBL'),obligationId:makeId('OBL'),title:data.get('title'),totalSatang:parseBahtToSatang(data.get('total')),installments});});
$('prevMonth').addEventListener('click',()=>{const date=new Date(Date.UTC(monthCursor.year,monthCursor.monthIndex-1,1));monthCursor={year:date.getUTCFullYear(),monthIndex:date.getUTCMonth()};selectedCalendarDate=`${monthCursor.year}-${String(monthCursor.monthIndex+1).padStart(2,'0')}-01`;renderCalendar();});
$('nextMonth').addEventListener('click',()=>{const date=new Date(Date.UTC(monthCursor.year,monthCursor.monthIndex+1,1));monthCursor={year:date.getUTCFullYear(),monthIndex:date.getUTCMonth()};selectedCalendarDate=`${monthCursor.year}-${String(monthCursor.monthIndex+1).padStart(2,'0')}-01`;renderCalendar();});
$('todayMonth').addEventListener('click',()=>{selectedCalendarDate=todayKey();monthCursor=monthFromDate(selectedCalendarDate);renderCalendar();});
$('calendarFilter').addEventListener('change',renderCalendar);
$('backupBtn').addEventListener('click',async()=>{try{const backup=await runtime.exportBackup();const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`YGPH_METROPOLIS_BACKUP_${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('settingsDialog').close();status('สร้าง Encrypted Backup แล้ว');}catch(error){$('settingsStatus').textContent=error.message;$('settingsStatus').classList.add('error');}});
$('systemLockBtn').addEventListener('click',()=>{for(const id of ['settingsDialog','calendarEditDialog','calendarCancelDialog']){const dialog=$(id);if(dialog?.open)dialog.close();}editingCalendarRecordId=null;runtime?.close();runtime=null;state=null;$('workspace').classList.add('hidden');$('commandNav').classList.add('hidden');$('gate').classList.remove('hidden');$('runtimeBadge').textContent='LOCKED';$('devicePin').value='';$('recoveryPassphrase').value='';status('',false,true);});
globalThis.addEventListener?.('ygph:daily-lifecycle',async()=>{if(!runtime||!state)return;try{state=await runtime.readState();if(!state)return;await ensureTodayGoal();render();}catch(error){status(error.message,true);}});
hydrateIcons();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});