import { openGreenfieldRuntime } from '../greenfield/runtime.mjs';
import { parseBahtToSatang, formatSatang, makeId, paymentIntentForQueue, parseInstallments, recordsFor, dashboard } from './ui-model.mjs';
const $=id=>document.getElementById(id);let runtime=null;let state=null;
function status(message,error=false,gate=false){const node=$(gate?'gateStatus':'appStatus');node.textContent=message||'';node.classList.toggle('error',error)}
function passphrase(){const value=$('passphrase').value;if(value.length<12)throw new Error('รหัสต้องมีอย่างน้อย 12 ตัวอักษร');return value}
async function jsonFile(input){const file=input.files?.[0];if(!file)throw new Error('เลือกไฟล์ก่อน');return JSON.parse(await file.text())}
async function ensureRuntime(){runtime?.close();runtime=await openGreenfieldRuntime({passphrase:passphrase()});return runtime}
function showWorkspace(){$('gate').classList.add('hidden');$('workspace').classList.remove('hidden');$('runtimeBadge').textContent='GREENFIELD';render()}
async function refresh(){state=await runtime.readState();if(!state)throw new Error('ยังไม่มีฐาน Greenfield');render()}
function renderList(node,records,domain){node.textContent='';const sorted=[...records].sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')));for(const record of sorted.slice(0,60)){const item=document.createElement('article');item.className='item';const amount=Number.isSafeInteger(Number(record.amountSatang))?`${formatSatang(record.amountSatang)} บาท`:'';item.innerHTML='<div class="item-head"><b></b><small></small></div><div class="muted"></div>';item.querySelector('b').textContent=record.title||record.type||record.recordId;item.querySelector('small').textContent=record.status||'';item.querySelector('.muted').textContent=`${record.type||''} · ${amount} · ${record.recordId||''}`;if(domain==='CALENDAR'&&record.status==='OPEN')attachCalendarActions(item,record);node.append(item)}if(!sorted.length)node.textContent='ยังไม่มีรายการ'}
function attachCalendarActions(item,record){const actions=document.createElement('div');actions.className='item-actions';if(['RECEIVE_CUSTOMER_PAYMENT','PAY_OBLIGATION','PAY_OBLIGATION_INSTALLMENT'].includes(record.type)){const input=document.createElement('input');input.placeholder='จำนวนเงิน';input.inputMode='decimal';const pay=document.createElement('button');pay.textContent=record.type==='RECEIVE_CUSTOMER_PAYMENT'?'รับเงิน':'ชำระ';pay.addEventListener('click',async()=>{try{const amountSatang=parseBahtToSatang(input.value);const intent=paymentIntentForQueue(record,amountSatang,{workflowId:makeId('WF-PAY'),transactionId:makeId('TX')});await runtime[intent.method](intent.input);await refresh();status('บันทึกและอ่านกลับแล้ว')}catch(error){status(error.message,true)}});actions.append(input,pay)}else{for(const target of ['COMPLETED','CANCELLED']){const button=document.createElement('button');button.textContent=target==='COMPLETED'?'เสร็จ':'ยกเลิก';button.addEventListener('click',async()=>{try{await runtime.calendarStatus({workflowId:makeId('WF-CAL'),queueId:record.recordId,status:target});await refresh();status('อัปเดตคิวแล้ว')}catch(error){status(error.message,true)}});actions.append(button)}}item.append(actions)}
function render(){if(!runtime||!state)return;const view=dashboard(state,runtime.project());$('homeBalance').textContent=formatSatang(view.ledgerBalanceSatang);$('homeRevision').textContent=view.revision;$('homeStoreCount').textContent=view.storeRecords;$('homeCalendarOpen').textContent=view.calendarOpen;$('diagnostics').textContent=JSON.stringify(runtime.diagnostics(),null,2);renderList($('storeList'),recordsFor(state,'STORE'),'STORE');renderList($('ledgerList'),recordsFor(state,'LEDGER'),'LEDGER');renderList($('calendarList'),recordsFor(state,'CALENDAR'),'CALENDAR')}
async function run(method,input){try{await runtime[method](input);await refresh();status('บันทึกและ durable readback ผ่าน')}catch(error){status(error.message,true)}}
$('unlockBtn').addEventListener('click',async()=>{try{await ensureRuntime();state=await runtime.readState();if(!state)throw new Error('ยังไม่พบฐาน Greenfield — ใช้ Evidence หรือ Backup');showWorkspace()}catch(error){status(error.message,true,true)}});
$('importEvidenceBtn').addEventListener('click',async()=>{try{const evidence=await jsonFile($('evidenceFile'));await ensureRuntime();const result=await runtime.initializeFromEvidence(evidence,{expectedPackageId:'FLOW-1786527289637',expectedRevision:28});state=result.state;showWorkspace();status(`Import ${result.status} · revision ${state.revision}`)}catch(error){status(error.message,true,true)}});
$('restoreBtn').addEventListener('click',async()=>{try{const backup=await jsonFile($('restoreFile'));await ensureRuntime();const result=await runtime.restoreBackup(backup);state=result.state;showWorkspace();status('Restore VERIFIED')}catch(error){status(error.message,true,true)}});$('showImportBtn').addEventListener('click',()=>$('evidenceFile').focus());
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(node=>node.classList.toggle('active',node===button));document.querySelectorAll('[data-page]').forEach(page=>page.classList.toggle('active',page.dataset.page===button.dataset.tab))}));
$('saleForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const amount=parseBahtToSatang(data.get('amount'));const received=parseBahtToSatang(data.get('received')||'0');run('sale',{workflowId:makeId('WF-SALE'),saleId:makeId('SALE'),ledgerTransactionId:received>0?makeId('TX'):undefined,calendarQueueId:received<amount?makeId('Q'):undefined,title:data.get('title'),amountSatang:amount,quantity:Number(data.get('quantity')),receivedSatang:received,dueDate:data.get('dueDate')||undefined})});
$('purchaseForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const due=data.get('returnDueDate')||null;run('purchase',{workflowId:makeId('WF-BUY'),purchaseId:makeId('BUY'),ledgerTransactionId:makeId('TX'),returnQueueId:due?makeId('Q'):null,title:data.get('title'),amountSatang:parseBahtToSatang(data.get('amount')),quantity:Number(data.get('quantity')),returnDueDate:due})});
$('withdrawForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);run('stockWithdrawal',{workflowId:makeId('WF-WD'),recordId:makeId('WD'),title:data.get('title'),quantity:Number(data.get('quantity'))})});
$('adjustForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);run('stockAdjustment',{workflowId:makeId('WF-ADJ'),recordId:makeId('ADJ'),title:data.get('title'),deltaQuantity:Number(data.get('delta')),reason:data.get('reason')})});
$('incomeForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);run('otherIncome',{workflowId:makeId('WF-IN'),ledgerTransactionId:makeId('TX'),title:data.get('title'),amountSatang:parseBahtToSatang(data.get('amount'))})});
$('expenseForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);run('expense',{workflowId:makeId('WF-OUT'),ledgerTransactionId:makeId('TX'),title:data.get('title'),amountSatang:parseBahtToSatang(data.get('amount'))})});
$('obligationForm').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const installments=parseInstallments(data.get('installments')).map(item=>({...item,queueId:makeId('Q')}));run('obligation',{workflowId:makeId('WF-OBL'),obligationId:makeId('OBL'),title:data.get('title'),totalSatang:parseBahtToSatang(data.get('total')),installments})});
$('backupBtn').addEventListener('click',async()=>{try{const backup=await runtime.exportBackup();const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`YGPH_METROPOLIS_GREENFIELD_BACKUP_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('สร้าง Encrypted Backup แล้ว')}catch(error){status(error.message,true)}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
